### ISSUE TITLE
Cannot start latest apk

### ISSUE THREAD

**Issue by iljah** [btcontract/lnwallet#102]
When starting latest version of apk (https://github.com/btcontract/lnwallet/commit/35f04d1477dd44f8bce7714b9351dc85099b808a) on (almost?) latest amazon fire screen turns black for a while and then I'm dropped back to app launcher. Version from few days ago (https://github.com/btcontract/lnwallet/commit/deddf1283a60a2176bf13915e42a5b7d4afb2fd6) worked. Is there easy way to see what is going wrong with latest version?

**Comment by btcontract** [comment]
I've just uploaded a new APK, it should enter an "emergency mode" with readable error report in case if anything goes wrong on startup. Can you try it and provide an error report?

**Comment by iljah** [comment]
Today's apk started fine, thanks!
