### ISSUE TITLE
BUG: Reverse open channel not working

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnwallet#104]
According to https://github.com/btcontract/lnwallet/issues/79#issuecomment-427873120 I tried to open a channel to my phone from my node to try it out. The channel opening times out.

My node is LND 0.5 and BLW is 0.2-80.

Note that I already had a channel between the two opened from the phone, I just wanted to try it out the opposite way.

I tried these scenarios:

* Phone screen off, initiated request, then unlocked the phone and opened BLW
* BLW open, "Wallet operational" status, phone unlocked, initiated request from LND
* "Open new channel" chosen, hit cancel, "Opening channel" screen, initiated request from LND

All cases time out.

**Comment by btcontract** [comment]
Did you make sure LND proposes to open a non-public channel? BLW will just ignore public channel requests.

**Comment by Kixunil** [comment]
Ah, that was the issue. Thanks!
