### ISSUE TITLE
Remove footguns: Disallow changes to the amount when paying >0 invoice

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnwallet#106]
When paying non-zero invoice, the wallet allows changing the amount. While it (correctly) doesn't allow to decrease it, allowing to change it might be confusing or even harmful to the user.

We've had many experiences with screwed-up on-chain wallets at Paralelna Polis Bratislava, where the wallet would pay incorrect amount and it broke the whole system. This is still causing us major headaches.

Repeating the same mistake on Lightning doesn't sound good to me. Even if it works for most applications today, it may be a major footgun. Disabling it is much safer.

Of course, if the request is for zero amount, it should allow changing the amount.

**Comment by btcontract** [comment]
How paying more can hurt a payee? The only way I can think of is when payee's software listens to exact amount requested which would be a wrong implementation in a first place. Ability to pay up to 2x more is enabled on a protocol level so such payments may arrive even if client GUI does not allow that.

**Comment by Kixunil** [comment]
> The only way I can think of is when payee's software listens to exact amount requested which would be a wrong implementation in a first place. 

That's the exact problem we've experienced with on-chain wallets and several plugins/frontends listening for exact amount. That's why I suggest to remove the ability to change the amount.

**Comment by Kixunil** [comment]
The problem is not that addresses are reused - a new address is generated for each payment. It's definitely questionable implementation (Why not accept more? Maybe because of legal issues?), but it leads to surprising problems.

So my suggestion is to try to avoid those problems based on experience we have (this was with several customers and is probably one of the reasons BitPay enforces BIP70).

**Comment by btcontract** [comment]
To clarify: do you mean off-chain or on-chain invoices here?

**Comment by Kixunil** [comment]
The problems I mentioned were all on-chain, however I suggest disabling all changes to amount for both on and off chain payments in order to prevent potential problems in the future.

There is another risk I forgot to mention: the user accidentally increases the amount and then requests a refund, which takes time. Recently, I had a pretty bad experience refunding one of the peers of Paralelna Polis node, who accidentally used push_amount without understanding it (not BLW, but that's unrelated). I would be quite unhappy to repeat the tedious refund process for yet another reason.

**Comment by btcontract** [comment]
OK, i'll update rules for on-chain payments such that it won't be possible to send less than a specified amount (if amount is provided at all).

As to off-chain payments, `push_amount` is only relevant for channel opening, BLW sets it to `0` and there's no way user can change it. 

It is already not possible to pay less than requested off-chain, but I'll keep an option to pay up to 2x of requested sum because it's a part of protocol and some implementations already send a bit more by default. In c-lightning case, if, say, `50 000 SAT` is requested a `50 000.034 SAT` may be sent so your software should always be prepared for that.

**Comment by Kixunil** [comment]
Seems like my communication skill sucks today. On-chain payments MUST be exact, not even higher is allowed, because too many systems expect the exact amount already. I've personally seen issues where a payment wasn't identified if the amount was higher. I know and agree those systems are terrible, but unfortunately, it's the reality. Samourai Wallet doesn't allow editing the amount for exactly this reason as well.

Push amount is completely unrelated to this, it wasn't even BLW, the point was that the refund process was tedious and I don't want to repeat any refund process anymore.

However, if other wallets change the amount by default, my argument about possible mishandlings falls apart. But let's not argue about this infinitely. I will collect data on LN usage in Paralelna Polis and let you know if my concerns about accidents are valid at all.

**Comment by Kixunil** [comment]
Great, thanks for consideration!
