### ISSUE TITLE
Problem with opening reverse channel on freshly installed wallet.

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnwallet#108]
I'm experiencing a problem with opening a reverse channel with freshly installed wallet. Steps to reproduce:

* Make sure you have a LN node (LND in my case) installed and topped with some coins.
* Generate a QR code for its address.
* Install a BLW on a phone
* Without doing anything else with BLW (besides backing it up), click "Open channel" and choose QR code
* Scan the QR code with the address of the node.
* You should see BLW on the list of connections of the remote node (LND)
* Try to open a channel from remote node (I did use `--private`, with 300000 sat capacity and tried with both 0 and 10000 sat push amout)
* No dialog is visible in BLW
* When you click back few times to return to the main screen the dialog is visible, but at this point BLW disconnected from the remote node, thus clicking OK does nothing.

The steps were tried several times, including after restarting the wallet. The phone was connected over Wi-Fi.

Expected behavior: the dialog informing about opening channel is shown regardless of screen user is on or at least at screens related to opening the channel.

Wallet version: v0.2-81 (from Google Play)
Android version: 8.0.0

**Comment by btcontract** [comment]
See https://github.com/btcontract/lnurl-rfc/blob/master/spec.md#1-incoming-payment-channel-request

**Comment by Kixunil** [comment]
I know that one should work, but it forces everyone to use `lnurl` scheme. I will try to implement it for my use cases, just wanted to have something useful meanwhile.
