### ISSUE TITLE
Desktop Wallet

### ISSUE THREAD

**Issue by fiatjaf** [btcontract/lnwallet#109]
I know nothing about Android stuff, but can this codebase be somehow reused to make a light desktop wallet?

**Comment by btcontract** [comment]
Yes, it can. No need to change core LN logic but would still require a lot of UI related desktop-specific work. 

Also, I'd probably recommend to use Eclair for this purpose since my implementation is absolutely minimal, for example routing stuff is not implemented at all since it's not feasible on mobile, but may be usable on desktop.

**Comment by d4amenace** [comment]
@fiatjaf why not just set up a full lightning node and remote RPC to a full Bitcoin node.

**Comment by btcontract** [comment]
@fiatjaf 
> Routing and stuff is done by Olympus servers, right?

I mean functioning as a routing node to transfer payments from third parties, that stuff is not present in code.

**Comment by fiatjaf** [comment]
Oh, right.

But exactly, I wanted an app that would work just like BLW for Android, without routing, relying on Olympus servers for a lot of stuff, everything a light, beginner user would want, but in his desktop instead of on Android. I wanted an app my mother could use without caring too much.

**Comment by fiatjaf** [comment]
@d4amenace I do that for myself, but I'm thinking about normal people here, and I can't offer my node to everybody (even less if I tell them it crashes sometimes). I also don't think Eclair will do well with a remote bitcoind (will it?), lnd doesn't like it a lot, but lightningd does. I'm also not thinking about offering this as a service (although I'm interested in running an Olympus server in the future).

**Comment by fiatjaf** [comment]
Well, anyway, this wallet has everything you could wish for a nocoiner to being using Lightning, you can even lose your phone and recover everything later with just the mnemonic seed!

Well, now that I know it is possible to run this code as a desktop app I'm inclined to learn Scala just to fork it, but since will take a lot of time for me, I'm asking and waiting to see if someone likes the idea and goes ahead with before :P
