### ISSUE TITLE
Testnet App Updates

### ISSUE THREAD

**Issue by brandoncurtis** [btcontract/lnwallet#110]
Hello!  I have the testnet version of the wallet installed on a couple devices, but I see that it doesn't come up in search anymore in the Play Store and it hasn't been updated since version 01.73 (mainnet is now 02.86 I believe).

testnet: https://play.google.com/store/apps/details?id=com.lightning.wallet
mainnet: https://play.google.com/store/apps/details?id=com.lightning.walletapp

Do you plan to update the testnet version of the app, or to add testnet support to the mainnet app?

Thanks for all of your work, this is a great wallet!

**Comment by btcontract** [comment]
I don't plan to further support testnet version, mainly using it only for internal testing now.

**Comment by brandoncurtis** [comment]
Lightning is early and many people still use the testnet extensively for development and testing.  Would you consider pushing an update for the testnet version?  Totally understandable though if you don't want to take time away from mainnet development.

**Comment by btcontract** [comment]
OK, if people still use it I'll update it. I was under impression that was not the case for some time now.

**Comment by btcontract** [comment]
Done, will be available in Google Play in a few days, APK is available here: https://github.com/btcontract/lnwallet/blob/testnet/app/app-release.apk
