### ISSUE TITLE
whats my nodes public key

### ISSUE THREAD

**Issue by Tschaul** [btcontract/lnwallet#111]
Hi,

thanks so much for your effort. I have a question: How can i find out the public key of the lightning node that is the wallet? 

At yalls.org i shall put in the public key of my node. When i later claim my tips i shall send a lightning request and it will verify that this request comes from the node with the corresponding private key.

https://yalls.org/payouts

**Comment by btcontract** [comment]
There's no easy way to obtain it currently, but since some services require it I'll add a way to get it in a next update.

**Comment by Tschaul** [comment]
Thats good to hear!

I thought i could somehow decode it from a payment request. It seams to be recoverable from the signature part. I am bit into crypto but not that deep. If i would manage to extract the pub key from there do you think it could work?

**Comment by btcontract** [comment]
Yes, sure. There is no need to recover it even, it's present directly as payee nodeId in a payment request. There's a service which does online decoding: https://lndecode.com/ but oddly enough it does not display a nodeId.

**Comment by Tschaul** [comment]
As far as I understand it that is because it is optional because it can be recovered from the signature. see the 'n'-Field in https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#tagged-fields

I will try to recover it and document my steps here: https://github.com/Tschaul/recover-pub-key

**Comment by btcontract** [comment]
Great, this is also fixed in https://github.com/btcontract/lnwallet/commit/492899156236360956cb1ad91cc81d9bf389a242, since next update it will be possible to obtain a NodeId by `Floating Button -> View Channel details -> Menu -> Share my LN Node Id`.
