### ISSUE TITLE
Bitpay / Payment Protocol Payments

### ISSUE THREAD

**Issue by drunnells** [btcontract/lnwallet#114]
I was unable to send a Bitpay payment with my BTC balance. I followed the "Open Wallet" link on the Bitpay payment screen a website, which opened the wallet and prompted me for an amount. I entered the exact amount from the payment screen but after clicking continue I received white "Emergency Mode" screen that gave me the option to view my seed phrase. I uninstalled the app and reinstalled from Google Play and restored my wallet, but received the same message again. Sending BTC to another Bitcoin wallet that I control DID work as expected, however. I was also able to send lightning payments without problem. Perhaps BitPay / Payment Protocol is not currently supported?

Error Report screenshot:
![screenshot_20181209-234519](https://user-images.githubusercontent.com/8787913/49711401-1f051000-fc0d-11e8-892f-6ab79c2535c1.png)

**Comment by btcontract** [comment]
Yes, BIP70 payment protocol is not supported in BLW. But crashing on scanning it is definitely not right and has to be fixed.

**Comment by btcontract** [comment]
https://github.com/btcontract/lnwallet/commit/18893f38597e559ee916e8766a19db6bddefbc0d
