### ISSUE TITLE
Feature Request: Variable Fee limit in an Advanced Settings view

### ISSUE THREAD

**Issue by juscamarena** [btcontract/lnwallet#115]

**Comment by btcontract** [comment]
Were there some kind of fee related issues? Off-chain fee limit is already variable and very permissive, as defined by this formula: https://github.com/btcontract/lnwallet/blob/master/app/src/main/java/com/lightning/walletapp/ln/LNParams.scala#L51-L52

**Comment by btcontract** [comment]
Closing this for now, please let me know if there are any issues still.
