### ISSUE TITLE
Sent BTC funds to wallet but cannot see them

### ISSUE THREAD

**Issue by RyanSepio** [btcontract/lnwallet#116]
Hello -

The transaction is verified but I cannot see the BTC I sent in the wallet on my phone.  

I used the receive funds>Bitcoin transaction address to send the funds from Coinbase.

What am I missing in the app?

**Comment by RyanSepio** [comment]
I have already saved the mnemonic code.  Actually even used it to restore the app again.

It has been sent and verified.  https://www.smartbit.com.au/tx/3e71b4f5746dd25531ab822d926727430fa06931ee04eadcbc6d2393b2d7d9f9

At the top it shows:

No on-chain funds
No off-chain funds
Connecting to Peers...

= 0 USD

**Comment by fiatjaf** [comment]
i would try restoring the wallet on Electrum using the mnemonic code (mark the BIP39 checkbox and selection SegWit native address type).

**Comment by btcontract** [comment]
"Connecting to Peers..." seems to be the problem here, normally it takes a few seconds at most to get some connections. 

Can you ckeck if a phone has a working internet connection right now? If yes, perhaps network access has been specifically restricted for a wallet app in system settings?

**Comment by RyanSepio** [comment]
Yes the phone has an internet connection.  Other apps can connect.

I checked the settings for the app and it says 0 data used.

I also checked that it has full network permissions.

**Comment by RyanSepio** [comment]
It is a Pixel 3 with Android 9 - security patch level 12/5/2018 Build PQ1A.181205.006

**Comment by RyanSepio** [comment]
This is what it looks like.

![image](https://user-images.githubusercontent.com/967158/49905648-c95a7e80-fe2b-11e8-94ee-dd40f1628d6d.png)

**Comment by RyanSepio** [comment]
I was able to access the funds with Electrum.  
Just curious why the Bitcoin Lightning Wallet is not able to connect.  
If there is anyway I can help you test let me know.

**Comment by btcontract** [comment]
What's interesting is that app has network access in general since it's got USD rates, looks like only socket connections to remote nodes fail. Can you try to change network type (wifi -> cellular or vice versa) and try again?

**Comment by RyanSepio** [comment]
Ok.  Solved it.   My phone was using office wifi and our Firewall was blocking the ports.  Once on mobile data all working fine.  So opened firewall ports for local internet as well.

**Comment by btcontract** [comment]
Great news, now I'll know where to look first if this case happens again.
