### ISSUE TITLE
More Currencies

### ISSUE THREAD

**Issue by swilliams96** [btcontract/lnwallet#12]
It would be good to support more currencies rather than just USD, EUR, CNY and JPY. I'm from the UK so would prefer to use the app in GBP and I'm sure people from other countries would appreciate being able to use it in their own currencies too.

Perhaps users could choose their currency in settings and then currency selection can be removed from the 'send payment' dialog entirely. Or alternatively allow users to choose which currencies (up to 4) show up on the 'send payment' dialog (and hide currency selection if only 1 currency is selected in settings).

**Comment by rdymac** [comment]
It would be great to add the real market price of Bitcoin in Venezuelan Bolivars (VEF) too: https://api.bitcoinvenezuela.com

**Comment by btcontract** [comment]
More currencies including GBP are now available.
