### ISSUE TITLE
UX/UI: visually distinguish opening a channel from other on-chain transaction.

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnwallet#121]
I was showing BLW/LN to a newbie and she was confused by the way BLW shows opening channel - as a spend. (Red with minus sign.) She thought the money was sent somewhere else. I'm not surprised.

I suggest changing such transactions to something like this:

`B -> L  1234` where B is Bitccoin logo and L is the lightning logo. The amount should be in black. This more clearly denotes what's going on. SImilarly, closing a channel should be indicated in same way, but opposite arrow (or the icons swapped, not sure which is better).

There may be some better form of showing it. What I want to say is that the current form is very confusing.

**Comment by fiatjaf** [comment]
The problem is red characters and the minus sign, right? That can be really confusing.

Instead of showing that money as _spent_ I suggest that you represent it as _frozen_, perhaps in blue and between brackets: `[10000]`.

**Comment by btcontract** [comment]
I've already made some steps in this direction, if you tap a channel funding tx you'll see it's of blue color and has special description:
![photo_2019-01-15_11-14-31](https://user-images.githubusercontent.com/9870980/51170364-f54ba280-18b6-11e9-8308-a31da195d67b.jpg)

Guess I could go further and make it blue in a payment list also.

**Comment by btcontract** [comment]
Looks like this now: 
![photo_2019-01-15_14-20-58](https://user-images.githubusercontent.com/9870980/51180318-d5c17380-18d0-11e9-8f76-8e05839e3e22.jpg)

Unless there are objections I'll proceed with this one.

**Comment by fiatjaf** [comment]
That's better, but the `+` is misleading.

**Comment by btcontract** [comment]
What would you rather see there? Brackets seem no less cryptic to me.

**Comment by fiatjaf** [comment]
`+` indicates an incoming transaction. People will they've earned bitcoin. I proposed brackets because they don't have a meaning, but if you don't like them use other sign, like a ~ or ¬ (of course you'll say these are cryptic) or no sign at all.

**Comment by btcontract** [comment]
Brackets and special color implemented in https://github.com/btcontract/lnwallet/commit/bb9eb903ece7629ae6b08252f095f04607dc929b

**Comment by Kixunil** [comment]
Wow, this was quicker than I could react! Very well, thanks a lot! :)
