### ISSUE TITLE
Allow zero-conf spending from push amount

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnwallet#125]
Spending from `push_amount` should be allowed without waiting for confirmation since in the worst case the channel won't open at all and the user loses whole `push_amount`. There's no reason to wait for confirmation.

Steps to reproduce the issue:

* open a channel from remote node with sufficient `push_amount` using lnurl
* try to pay an LN invoice (amount < `push_amount`) before it confirms

What happens

A dialog appears saying the funding transaction needs at least 6 confirmations.

What should happen

The invoice should be payable immediately.

Note: there's a real world use case in Paralelna Polis Bratislava, where people buy cryptocurrencies and want to pay with them immediately. Currently we are forced to recommend LTC to them and even that forces us to wait several minutes. Allowing zero-conf payments would allow us to greatly improve UX and not promote altcoins to the newcomers.

**Comment by btcontract** [comment]
This would require a protocol change. It's not that only my wallet forbids this, no peer currently would accept a payment for an opening channel.

**Comment by btcontract** [comment]
Actually in theory this may not require a protocol change if one can set a confirmation threshold for channel to become open to zero. BLW currently does not support this but enabling this is easy. Not sure how other implementations behave currently.

**Comment by btcontract** [comment]
After thinking about it a bit this seems like a great idea to me. If other projects are super busy with different stuff (which is probably the case) I'll just go ahead and implement this in BLW and a fork of Eclair, would you be interested to use such a fork?

**Comment by Kixunil** [comment]
Great! I don't use Eclair (neither Android nor daemon), but if it happens that Eclair daemon would allow this and `lnd` not, I'd strongly consider migrating to Eclair to solve this problem ASAP.

However, I looked at `lnd` code and I can't find anything that filters-out this case, so maybe it can work without any changes to `lnd`?

**Comment by btcontract** [comment]
The way it works in Eclair is there are no explicit filters either, but a fresh channel enters a `WAITING` state by default and awaits for enough blockchain notifications to become `NORMAL`, so zeroconf special case won't work and has to be added. I suppose in LND it's similar but I'm not familiar with it.

I've asked Eclair devs what they think about it here: https://gitter.im/ACINQ/eclair If they won't mind I'll bake all this in main repo and there won't be a need for a fork even.

**Comment by btcontract** [comment]
Also, apparently you've been working on `lnurl` spec, just want to let you know a testnet APK is available which fully supports `lnurl` and will support zeroconf channels: https://github.com/btcontract/lnwallet/blob/f42c116949b7a91cff3dee7d0bb39b8e276785b0/app/app-release.apk

**Comment by btcontract** [comment]
Here's the software (testnet for now):

https://github.com/btcontract/lnwallet/blob/testnet/app/app-release.apk

https://github.com/btcontract/eclair/commits/turbo-channels-demo
