### ISSUE TITLE
Cannot connect to C Lightning node

### ISSUE THREAD

**Issue by d4amenace** [btcontract/lnwallet#126]
I'm trying to establish a channel to my c lightning node and I get the error message that channel backups are not supported.

**Comment by btcontract** [comment]
Recompile it using `./configure --enable-experimental-features`, morei nfo here: https://github.com/ElementsProject/lightning/issues/2170

**Comment by d4amenace** [comment]
An upgrade to 0.6.3 and this worked perfectly.
