### ISSUE TITLE
Cannot connect to non-listed node

### ISSUE THREAD

**Issue by d4amenace** [btcontract/lnwallet#127]
I cannot connect to my node which I have the IP broadcasting as 0.0 0.0 (for privacy) but when I attempt to connect in the app I use the real web address. The app still refuses to connect only recognizing the zeroed out address.

**Comment by btcontract** [comment]
Can you provide a node URI you use when trying to connect?

**Comment by d4amenace** [comment]
Not an issue with BLW.
