### ISSUE TITLE
"bitcoin:" URI handling support?

### ISSUE THREAD

**Issue by andronoob** [btcontract/lnwallet#129]
If a URI like "bitcoin:1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa" is copied, BLW won't recognize it as a valid bitcoin address.

**Comment by btcontract** [comment]
Have just tried it out on `0.3-108`, both sharing and copy/pasting works. What's your app version? (can be seen by tapping a settings gear).

**Comment by andronoob** [comment]
It doesn't work in "close channel to specified address"

**Comment by btcontract** [comment]
Indeed, fixed in https://github.com/btcontract/lnwallet/commit/b8688023cbee6341c040ddb0951838a67951d3ca
