### ISSUE TITLE
Poor Simplified Chinese Translation

### ISSUE THREAD

**Issue by cyanlink** [btcontract/lnwallet#13]
Most Chinese Simplified Texts are machine-generated and in poor quality. I'm a native speaker and can fork & pull request. Is there anything I need to know before I start?

**Comment by btcontract** [comment]
Hi, thanks for helping on this! All the texts are contained in https://github.com/btcontract/lnwallet/blob/master/app/src/main/res/values-zh/strings.xml, that file is the only location which needs to be edited.

**Comment by cyanlink** [comment]
@btcontract Thank you, I know the basis of Android and Java so I can deal with those placeholders.

**Comment by btcontract** [comment]
Another thing is I still use a rather old version of Android Studio (v3.3.2), a project may not compile on newer versions. But for this translation task an xml file can be updated in any simple editor.
