### ISSUE TITLE
Ability to establish a TOR onion-routed channel using a socks5 proxy

### ISSUE THREAD

**Issue by d4amenace** [btcontract/lnwallet#130]
I was wondering if this capability was already availale in the wallet.  If not, will there be an upgrade that allows for the on/off capability of establishing a socks5 proxy in app?

**Comment by btcontract** [comment]
> I was wondering if this capability was already availale in the wallet.

Yes, it is available, more info here: https://lightning-wallet.com/using-lightning-wallet#tor-support

**Comment by d4amenace** [comment]
thx.
