### ISSUE TITLE
Unable to open a channel to LND nodes based on current master

### ISSUE THREAD

**Issue by drunkenclam** [btcontract/lnwallet#133]
If you want to open a channel to an LND node that is running current master, it fails with

[node] does not support data loss protection

Reproducable with Moneni node:
https://1ml.com/node/03295d2e292565743a40bd44da227a820f8730877bc3dfadebade8785bcf355258

**Comment by btcontract** [comment]
Data loss protection is an optional feature which is used to refund lost channel balance in case if user loses wallet data. BLW disallows creating channels with remote nodes which don't support it. LND supports this feature in principle but seems like it's disabled by default now.

**Comment by btcontract** [comment]
It was actually a bug in BLW, fixed in https://github.com/btcontract/lnwallet/commit/29dbf4335d476949f770b60fc5f8ed198e6c3255, update will be rolled out in a Google Play within a few days.
