### ISSUE TITLE
Error message from node disappears too quickly

### ISSUE THREAD

**Issue by iljah** [btcontract/lnwallet#137]
Tried to open new channels to bitrefill node and first time I couldn't see the error because it disappeared in less than half a second I think. Second time I tried the same, the message was up for about a second which also wasn't enough time to read the whole message but I'm guessing bitrefill complained that minimum channel size is 0.01 btc.

I suggest errors should stay up longer (like 5-10 s) but could be dismissed by clicking anywhere if someone is in a hurry. Was using [this](https://github.com/btcontract/lnwallet/blob/master/app/app-release.apk) from about 1 h ago

**Comment by btcontract** [comment]
Replacing toast with a popup window there is surprisingly involved so for now I've at least made a toast to be displayed for a longer time period in https://github.com/btcontract/lnwallet/commit/2420442fe92c310871c5c3bd1db378c7b2359661.
