### ISSUE TITLE
App crashes after latest update

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#139]
Device: Samasung Galaxy Tab S2.
Crash on opening every time.
![Screenshot_20190618-214529](https://user-images.githubusercontent.com/19826327/59718626-761a1c00-9212-11e9-9ab0-6de09589468d.png)
![Screenshot_20190618-214526](https://user-images.githubusercontent.com/19826327/59718635-7b776680-9212-11e9-8354-c876f338755c.png)
![Screenshot_20190618-214514](https://user-images.githubusercontent.com/19826327/59718643-7fa38400-9212-11e9-9654-c617c482192a.png)

**Comment by btcontract** [comment]
Yes, I've already issued another update to reverse this problematic one. Does applying a new update helps?

**Comment by irekzielinski** [comment]
Yes, works now. Thanks!
