### ISSUE TITLE
Turbo payment stuck

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnwallet#141]
Problem:

When trying to pay invoice to the peer who's opened a yet unconfirmed Turbo channel, the payment is stuck.

Detailed description:
* Peer runs Eclair - your fork to allow Turbo
* Peer opened a channel to another node before, this channel is in WAIT_FOR_FUNDING_CONFIRMED state. Let's called this node `C`
* Peer opened a Turbo channel with BLW using LNURL, it's in WAIT_FOR_FUNDING_LOCKED
* BLW had a confirmed channel to `C`

Since BLW -> C -> Eclair is impossible, I expect the wallet to try directly BLW -> Eclair, which is Turbo

How can I debug this?

**Comment by Kixunil** [comment]
Sorry, found the issue. I was using SSH tunnel to connect to trusted node. I guess there was some problem with the tunnel or trusted node config, will need to investigate. It worked after turning off trusted node.

**Comment by btcontract** [comment]
Do you mean trusted on-chain node? BLW does require for both LN peer and some Bitcoin node to be connected to even attempt a Lightning payment because it needs to know a current chain height to construct an LN payment and not get it rejected.

**Comment by Kixunil** [comment]
Yes, on-chain node. I've ssh-forwarded localhost:8333. Strangely, it worked correctly before. Is it possible that the newest update broke it?

**Comment by btcontract** [comment]
No, there were no changes which could affect this. Once trusted node is set BLW needs a restart to actually start using it so maybe it was still using random nodes at the time.
