### ISSUE TITLE
Payments via turbo channel not forwarded

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnwallet#142]
Description
---------------

Payments are not *forwarded* via turbo channel. Direct payments work correctly.

Environment
-----------------

* Client (A) BLW freshly installed from Google Play
* [Eclair fork](https://github.com/btcontract/eclair/tree/turbo-channels-new-api) with turbo support on server (B) side with channel opened to the payee (C).
* Turbo channel opened from B to A with sufficient push amount. Opening done using [lnch-vekslak](https://github.com/Kixunil/lnch-vekslak)

Steps for reproducing the issue
----------------------------------------

1. Payee (C) generates an invoice (QR code)
2. A scans QR code - can't pay it with message that the channel isn't opened.
3. Direct payment from A to B works.
4. Direct payment from B to C works.

The last three points were tested in that order.

Expected behavior
------------------------

Forwarding should work because A can't cheat B. Actually, in the worst case A loses money, so it makes sense for A to try to spend it.

**Comment by btcontract** [comment]
Probably `B - C` channel is not visible to BLW for some reason. Doubt it's specific to turbo nature of `A - B` channel, otherwise we'd be hearing a lot of complains from users.

Do payments to other places work? (yalls for example)
How old is `B - C` channel, what is the capacity there?

**Comment by Kixunil** [comment]
Strangely `B - C` is not visible at 1ml. The capacity should be 1500000 sat. Didn't try others yet.

**Comment by btcontract** [comment]
> Strangely B - C is not visible at 1ml

This is most likely the reason, it seems somehow channel is not announced yet.

Is the funding for `B - C` at least 6 blocks deep?
Do you control both `B` and `C` nodes? Both of their signatures are required for an announce, perhaps a restart would help.

**Comment by Kixunil** [comment]
The `B - C` channel has > 450 confirmations.
I restarted both nodes, now the channel is visible on 1ml.

Unfortunately, it still doesn't work. :( However, the message is "Failed and returned" now.

**Comment by btcontract** [comment]
Propagation may take some time occasionally, should definitely normalize within a few hours unless this is something new, please let me know.

**Comment by btcontract** [comment]
Also it may in fact work already, but `B - C` channel maybe returning an error. Detailed bug report can be obtained by tapping a failed payment and then "Share debug info" (with a caveat: debug info is not persisted, will be erased after app restart).

**Comment by Kixunil** [comment]
So we tested it after the channel opened and it worked. (Although considerably slower than `D - C` direct payment, where `D` is also BLW - if you have any tips to speed this up, it'd be very helpful.)

We tried second time on another two devices - and they worked. Closing this now, will reopen if something comes up.

Thanks a lot!
