### ISSUE TITLE
lnurl callback just appends '?params', ignores if there's already a '?' in the URL

### ISSUE THREAD

**Issue by fiatjaf** [btcontract/lnwallet#145]
If on a lnurl withdraw reply from the service you get `"callback": "https://service.com/x?y=z"` BLW will call it with `https://service.com/x?y=z?k1=...&pr=...`, which breaks everything.

It could detect if there's a `?` already and then apply its own parameters with `&k1=...&pr=...`.

**Comment by btcontract** [comment]
yeah, possible `?` this should be taken into account.

**Comment by fiatjaf** [comment]
When doing a login the problem is even worse, as the initial lnurl is _required_ to have querystring params (k1 and tag=login), but BLW calls the URL with something like:

```
/lnurl-login?tag=login&k1=banana?k1=[B@d7cca81&sig=&key=0226a0b9de7a671d4cebd97a3fb34c656c0d1b203e53a2b6712591c49fb335068e
```

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/1bdef52552ea0a55adc760686209eb30fdc081d6
