### ISSUE TITLE
lnurl-login call doesn't provide signature

### ISSUE THREAD

**Issue by fiatjaf** [btcontract/lnwallet#146]
Besides suffering from the same querystring problems described in https://github.com/btcontract/lnwallet/issues/145, when performing a login the `k1` is borked and `sig` is empty.

If the initial lnurl is `https://testurl.example.com/lnurl-login?tag=login&k1=378be88a4da486f610b94af4768ffbbff089ec78be6dfd3a312030a828087b36` the callback hits at:

```
/lnurl-login?tag=login&k1=378be88a4da486f610b94af4768ffbbff089ec78be6dfd3a312030a828087b36?k1=[B@2509b20&sig=&key=0226a0b9de7a671d4cebd97a3fb34c656c0d1b203e53a2b6712591c49fb335068e
```

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/911efbd35f5b7a223bdc1d58011adefe030e69f2
