### ISSUE TITLE
Add X button on channel details window

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#15]
Hi, 

I think should have a X button on top right of channel details window. 

Something like this:

![photo5152327456902981638](https://user-images.githubusercontent.com/1178856/35537907-240ae0ce-0533-11e8-9c73-37664188b7c5.jpg)

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/c81b668aa6b2eb05df5804e3f67ce693ab5cd41f
