### ISSUE TITLE
App shortcut for opening QR code scanner

### ISSUE THREAD

**Issue by Iffabled** [btcontract/lnwallet#150]
Android allows to create up to 5 [app shortcuts](https://developer.android.com/guide/topics/ui/shortcuts/), that can be used to quickly access some app activities from the launcher. A shortcut to quickly access the QR code scanner would make it much easier to access it.

**Comment by btcontract** [comment]
Sounds interesting, will look into that.

**Comment by fiatjaf** [comment]
Also a shortcut to create an invoice.

**Comment by btcontract** [comment]
Added in https://github.com/btcontract/lnwallet/commit/d7d673801954e17f49f76a6735e1e5d1b2c76e0a
