### ISSUE TITLE
Changing IP of channel partner

### ISSUE THREAD

**Issue by blacktemplar** [btcontract/lnwallet#154]
My channel partner recently changed his IP address and the channel is now always offline (I assume BLW tries to connect to the old IP). How can I change this? Is it possible to change the IP of the channel partner without closing and reopening the channel?

**Comment by btcontract** [comment]
Yes, that's most likely what is happening, but BLW tries to update remote node IP automatically if channel keeps being offline during 20 seconds after app launch.

If channel consistently stays offline even after 20 seconds that could mean two things:
1. Remote node is offline.
2. Remote node has not announced an updated IP address on public graph.

Can you provide a remote nodeId? This way I'll be able to find out what is going on.

**Comment by blacktemplar** [comment]
Thanks for your very fast answer, it helped. I think the problem is that the remote node has not announced the new IP (what you mentioned in 2.), I will check this and report here later if it was a problem of the remote node in which case this issue can be closed.

**Comment by btcontract** [comment]
OK, this can also be checked on explorers like 1ml.com: if old IP is still displayed there then a new one is very likely not announced yet for some reason.

**Comment by blacktemplar** [comment]
Everything works now after the remote node announced the new IP. Thanks for your help!
