### ISSUE TITLE
Lost funds when testing ChannelAcceptor of lnd

### ISSUE THREAD

**Issue by Kixunil** [btcontract/lnwallet#157]
I wrote a simple script to reject mobile wallets using [ChannelAcceptor API of LND](https://api.lightning.community/#channelacceptor). I tried to open a channel from my BLW to the LND instance several times, and when the script was crashing, the opening failed (due to timeout, I guess). Eventually I managed to fix it to not crash. To my surprise, BLW still sent the money to some 3... address, while opening no channel (it's not listed in BLW nor in LND). It currently shows zero balance.

I killed the script in order to not cause loss of funds of someone else. I'm not sure if I should publish it. I can send it directly over e-mail.

**Comment by Kixunil** [comment]
I've published the code as private repository and sent you an invite.

**Comment by btcontract** [comment]
This is strange because 3... address does not have anything to do with channels. Opening procedure itself is designed such that channel gets saved to db first, then funding gets spent. Are you absolutely sure this is not some unrelated spend? Can you reproduce this, say, on testnet?

**Comment by Kixunil** [comment]
Damn, shit, the website containing the QR code for LN URI also had a QR code for off-lightning donation and I didn't notice I accidentally scanned that one. Sorry for false alarm.
