### ISSUE TITLE
Clarify why F-Droid shows the NonFreeNet warning

### ISSUE THREAD

**Issue by squatica** [btcontract/lnwallet#16]
NonFreeNet means that the app depends on some server infrastructure which is not open source. But as far as I can tell from the explanation at the project homepage, this wallet only talks to the lightning network which is open source, TOR which is open source, and Olympus servers, which is also open source. So what prompted F-Droid to add that warning?

It should be either clarified in the description on F-Droid, or ideally remove the cause for the warning.

**Comment by btcontract** [comment]
It's because smartbit.com.au is a built in block explorer and there's no ability to change it, exact reasoning is in this thread: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6165

**Comment by squatica** [comment]
Ah, that's ok, thanks for the info. It would still be nice to have this information directly in the F-Droid app description for other people, at least for the time being. In the future it would be nice if the block explorer url was configurable, anyone can self-host something like this: https://github.com/iquidus/explorer and just point the Lightning Wallet to their own server which would remove the need for this anti-feature.

**Comment by yilmzfurkan** [comment]
Smartbit has already been replaced with mempool.space https://github.com/btcontract/lnwallet/commit/0a1f23d28427cdbaec786d23eff92b148f1c58e9 which is open source. https://github.com/mempool/mempool

**Comment by squatica** [comment]
That's even better, mempool.space is my favourite. I didn't even know it was open source! Thanks!
