### ISSUE TITLE
No payment channel found, but missing channel balance not returned

### ISSUE THREAD

**Issue by swilliams96** [btcontract/lnwallet#16]
I had a channel open with the _endurance_ node since the 22nd January and haven't opened the Lightning Wallet app to do any testing in the last few days as I have had exams. When I opened this app again recently, my Lightning channel is apparently no longer open, but I have not had the channel balance reimbursed from a channel closure so the balance I used to open the channel has just disappeared.

**Screenshot showing that I have no open channels:**
![image](https://user-images.githubusercontent.com/26005963/35589259-2a88f0d0-05fb-11e8-9dbd-4b1cc7e2f75d.png)
I expected to see my 15,000,000 sats channel open with _endurance_ but instead I do not have any channels open. I received no notification that the channel was closed and there is no incoming transaction reimbursing the unspent amount in the channel. It's likely not just a UI bug as my wallet received exactly 1.3 BTC from the faucet initially and now has just under 1.15 BTC, so (besides fees for opening and closing of various channels) the missing balance is equal to the 0.15 BTC balance of the missing channel.

**Screenshot showing no incoming channel closure funds:**
![image](https://user-images.githubusercontent.com/26005963/35589030-5d4ca95e-05fa-11e8-881c-6d62f1244d18.png)
The top transaction in the screenshot is the channel **opening** transaction for the payment channel, which was for 15,000,000 sats and can be viewed on smartbit [here](https://testnet.smartbit.com.au/tx/4f52a3d7e30b39de7bb06f360ddc49c066dfc058fe8d3bc6274f5cf99c27511f).

Has the _endurance_ node cheated me when my phone wasn't online to contest the cheating? I don't think this is what's happened as I've never got to a point where 100% of the channel balance was to be  sent to the _endurance_ node, so I'm not sure what's happened here.

I doubt this a problem specifically with this wallet (it is more likely a problem with Eclair). Also I'm not sure if this could be related to #14 in any way as my preceding channel was also force closed on the 17th January at 16:27 (shown in my second screenshot above) after attempting to make a lightning payment to (_I think_) Yalls.org.

Additionally, my app says that I have 0 storage tokens left. I'm not sure if this detail is related but I'm fairly confident I still had a large amount left as I have only opened and closed approximately 3 channels with this wallet. Perhaps it could be an issue with the Olympus server my channel was encrypted and backed up to?

**Comment by swilliams96** [comment]
My app is now on _v0.02-9_ so it must have automatically updated between when I first opened the channel and when I reopened the app again a few days later. Could it be that my local channel data was wiped when updating the app version?

**Comment by btcontract** [comment]
Yes, two updates with breaking changes were issued, one last week and another just yesterday. Those updates switch to new database files in order to avoid runtime crashes when trying to parse old data formats. I've added notices like this on app page:

![123](https://user-images.githubusercontent.com/9870980/35590679-4128cf4e-0610-11e8-9c51-5bf60f7e4bc5.png)

but of course there's no way to view them during automatic updates, sorry about that!

**Comment by btcontract** [comment]
Both channels and storage tokens are stored in a same database file so that's also a reason why no more storage tokens left.

**Comment by swilliams96** [comment]
Ah brilliant okay, glad to know this is all as expected and not some elusive bug! 😀
