### ISSUE TITLE
Set bitcoin unit popup appear when search is active

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#18]
1- Click search button
2- Click "near" the search field

The set bitcoin unit popup appear but it shouldn't

![photo5163868820006348740](https://user-images.githubusercontent.com/1178856/35756106-22f81fb4-0851-11e8-8a49-ca919bd99043.jpg)

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/98df4c371adfc04f0ac4e2e75a807e04d4ab9b0b
