### ISSUE TITLE
Paying from a mobile browser request should automatically redirect to browser after payment is successful done.

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#19]
To reproduce:

1- Go to https://starblocks.acinq.co/#/ using an android using any browser app.
2- Add a product to cart and click pay. Choose open with Testnet wallet.
3- Will open lightning-wallet, so click pay.

Suggestion: When you click pay, and the payment is successful, the browser window should automatically reappear.

**Comment by swilliams96** [comment]
Unfortunately I'm fairly sure this isn't possible in an android app. You're right though, it would be really nice to implement if it were possible.

**Comment by btcontract** [comment]
It's possible technically but this is one of those cases where software tries to be too smart where it should not (in my opinion).

**Comment by swilliams96** [comment]
I agree. Accurately determining if the user wants to go back to the browser after successfully completing a payment would be incredibly difficult. I think the small benefit in a handful of cases would be outweighed by the times that users would get annoyed at the app pushing them "back" to the browser when it shouldn't, especially considering swapping apps is not very difficult to do manually.

It's a nice suggestion though - any ideas to improve UI I think should be welcomed for discussion, as good user experience is what will separate this app from any other mobile Lightning wallet apps.

**Comment by btcontract** [comment]
Reopening due to popular demand. Will work as follows: successful payment gets an app closed and user sent back to a previous app, but only if payment request comes from tapping `lightning:` links in mobile environment, so closing won't be happening when scanning a QR on another screen for example.

**Comment by btcontract** [comment]
Implemented in https://github.com/btcontract/lnwallet/commit/4835a97e9741e2b89dad557d7d0b518e1834c874
