### ISSUE TITLE
Lenny face & blank error when opening new channel?

### ISSUE THREAD

**Issue by swilliams96** [btcontract/lnwallet#20]
I'm trying to open a new channel, but every time I try I either get a Lenny face or a blank error message. Some nodes give a Lenny face before the "Fund a payment channel" popup shows. Others will allow me to choose a channel capacity and after inputting my wallet passcode it will then show a blank error message. In both cases a channel is not opened by the wallet. 

**Screenshots:**
![error1](https://user-images.githubusercontent.com/26005963/36006904-95c1e896-0d37-11e8-850f-6a5beb63b819.png)
![error2](https://user-images.githubusercontent.com/26005963/36007096-b766c024-0d38-11e8-9b61-a4e0d010d389.png)

**Comment by swilliams96** [comment]
Sorry, I'm using version v0.04-16 of the app.

**Comment by swilliams96** [comment]
It looks like the blank error is occurring whenever I attempt to open channels with larger balances? For smaller balances it successfully checks my passcode and lets me choose a fee (standard or priority), though I haven't tested if it will actually proceed to make the channel opening transaction as I wanted to test which value were being rejected and which were being accepted.

Below are some channel balance values I tested with the yalls.org peer, though it looks like it's not specific to this one peer, as the odd values I tested again with other peers had the same results as the yalls.org peer.

To reproduce: I selected the yalls.org peer from the peer list, inputted the balance into the input field and then it either threw a blank error like the second screenshot in my original issue or it allowed me to proceed with the channel opening process. Checked boxes in the below list mean that the app allowed me to proceed to input my wallet passcode without any blank error being thrown, whereas unchecked boxes mean that it closed the channel funding popup with a blank error immediately after pressing "next" on the first payment channel funding popup, returning me to the peer list.

- [ ] 15,000,000 sats
- [ ] 14,999,999 sats
- [ ] 12,345,678 sats
- [ ] 12,000,000 sats
- [ ] 11,999,999 sats
- [x] 11,975,000 sats
- [x] 11,950,000 sats
- [x] 11,900,000 sats
- [x] 11,750,000 sats
- [x] 11,500,000 sats
- [x] 11,250,000 sats
- [x] 11,500,000 sats
- [x] 11,000,000 sats
- [x] 10,000,000 sats

It looks like for every channel balance over _some value_ in the range 11,975,000-11,999,999 sats the app is throwing the blank error when attempting to open a channel. My wallet balance is 104,534,295 sats so it's definitely not that I don't have enough wallet balance...

Really not sure what this could be - let me know if there's any more information I can provide.

**Comment by btcontract** [comment]
Once again sorry for confusion.

Lenny face is when a remote peer immediately disconnects or when connection could not be established at all, probably because a peer is offline (there is no easy way to determine peer liveness so there are lots of dead peers on the list).

Blank popup is when a peer sends a remote error because it does not like something about our proposed channel conditions, but error description is empty (which is not nice of peer, wallet currently assumes a remote error always have some meaningful description).

**Comment by swilliams96** [comment]
Ah I see. It would probably be best to not use a Lenny face in that case haha. Something like "_The remote peer could not be reached. Please try a different peer_." instead. And for the blank error popup potentially an `if` statement could be used to check if the remote peer's sent error description is empty and if it is then show an default error message such as "_The remote peer refused channel creation with these parameters. Please try again with a different channel balance, or try a different peer._" or something along those lines. Hopefully that will be enough to prevent confusion to any users that experience this error in future. 😀

**Comment by btcontract** [comment]
Sure, all that will be updated accordingly. Thanks for the message texts, I won't need to come up with them by myself now.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/d1b86c88400b1efc345124b5e443b152691afab3
