### ISSUE TITLE
Generate additional receive addresses for on-chain payments

### ISSUE THREAD

**Issue by dleshem** [btcontract/lnwallet#21]
I sometimes need to receive multiple on-chain payments in parallel, e.g. from two different payers.

BLW's UI only shows one (the next "unused") receive address, so I must either-

- reuse the address for both transactions, which has privacy and security implications.
- wait for the first transaction to broadcast and only then generate a new receive address, which takes days in some scenarios (e.g. exchange withdrawal).

It would be very useful if the UI offered a way to generate additional unused receive addresses.

**Comment by btcontract** [comment]
Implemented in https://github.com/btcontract/wallet which is a successor of BLW.
