### ISSUE TITLE
Missing resources?

### ISSUE THREAD

**Issue by ehanoc** [btcontract/lnwallet#23]
Hey, did you forgot to commit the following resources? 

ic_settings_white_24dp
ic_add_white_18dp

Cheers

**Comment by btcontract** [comment]
I did, thanks for noticing!
Also, just in case, master is not compilable right now as I'm committing my current unfinished work there (really should have made a separate branch, I know). This one compilable: https://github.com/btcontract/lnwallet/commit/04d80eca56adbcaf5a9734a9d15c91a9177a5acb

**Comment by ehanoc** [comment]
Aha! Just noticed wasn't compiling! Thanks. I'll keep an eye once you push something. I'm looking for some lightning project to play around and contribute.

**Comment by btcontract** [comment]
Perhaps now is not the best time: a project is under heavy development and all the current tasks require a very specific knowledge and expertise. That said, what's your passion? Do you happen to be an expert in graph algorithms?

**Comment by ehanoc** [comment]
Well, i have experience in crypto (btc, monero & ethereum smart contracts). Graph algorithms, yes, i've implemented a few different ones several times, mostly in LISP though. 

But I was mostly interested in contributing because i do have a few pet projects that i was going to support lightning anyway. I was looking to contribute to projects than then it could used as a library and help adoption. 

What do you need specifically ?
