### ISSUE TITLE
Close the lightning payment request window if the payment request is paid

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#25]
Close the lightning payment request window if the payment request is paid.

**Comment by btcontract** [comment]
Actually after further thinking about this I've decided to not implement this feature. One of the main reasons a QR code is displayed on a separate page it to not let a payer see your balance when you display a code to them. Instantly closing a QR page defeats that purpose. Perhaps https://github.com/btcontract/lnwallet/issues/47 is a better idea after all.
