### ISSUE TITLE
No ability to rename channels

### ISSUE THREAD

**Issue by nanotube** [btcontract/lnwallet#3]
There doesn't seem to be the capability to rename the channels. Channels that are opened via node explorer have nice pretty names, but channels opened via QR codes are just stored under IP address, and it would be nice to be able to edit channel metadata to give them meaningful names.

**Comment by nanotube** [comment]
Thank you for reviewing the issue! Could you discuss why you marked as wontfix?

**Comment by btcontract** [comment]
There's a mechanism in a wallet which tries to automatically update remote node parameters if it's offline for a long time, assuming that peer IP address has changed. Besides IP it also updates node alias and this will be clashing with manually provided alias. 

Accounting for this is possible but adds complexity and generally this is not an essential functionality so I'd just prefer to leave all as is here.

**Comment by nanotube** [comment]
I see, makes sense, thank you :)
