### ISSUE TITLE
Should be able to open channels directly from other bitcoins wallets.

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#30]
I would like to open channels on ln wallet without being necessary first send bitcoins to ln wallet.

**Comment by Perlover** [comment]
+1

**Comment by Perlover** [comment]
I think it's related
https://github.com/btcontract/lnwallet/issues/79

**Comment by btcontract** [comment]
Kind of solved using `lnurl` + push amount.
