### ISSUE TITLE
[question] Possible to connect to a node without funding a channel?

### ISSUE THREAD

**Issue by Cannon-Ciota** [btcontract/lnwallet#31]
To onboard merchants to the lightning network it would be nice to be able to open an inbound channel to them, or to users who I am needing to pay. Though with mobile devices such as phones they do not have a static ip address they would have to first connect to my lightning node. Is this possible to

1.  BLW  to CONNECT (not fund a channel) to my lightning node?
2.   Once I see the connection on my end I verify their public key, then I FUND CHANNEL to them.
3. They can now receive on lightning.

Does BLW have the option to connect to a node without opening a channel? Opening a channel to mine first is not an option because not all lightning nodes support multiple channels per peer.

**Comment by btcontract** [comment]
Yes it's possible:

1. Scan a node QR in BLW that will take user to a channel opening page, do nothing  (there will be a popup offering to fund a channel from BLW side, may be dismissed).

2. issue an opening offer from your node while BLW is connected like that. Proposed channel must be private and BLW node id should be known (it can be obtained from menu at "channel details" page in BLW).

Also out check https://github.com/fiatjaf/lnurl-rfc/blob/master/lnurl-channel.md which simplifies this flow and example implementation at https://lnbig.com/#/ (Inbound channel on you).

**Comment by Cannon-Ciota** [comment]
Thanks @btcontract so from the "open new channel" menu as I understand it right? Then BLW initiates a connection while on the popup before continuing?

I'm running c-lightning. And I am aware of lnurl. I did consider lnurl but I did not want to install that functionality for security reasons. I was afraid of the extra software opening up more security vulnerabilities and attack vectors. Especially with the code not being security audited. If a lightning node is going to contain any money on it I only want to install bare minimum required software that I can get by with. 

This may make a good feature request which I can open up separately if needed.
1. A "connect only, await channel open from node" feature.
2. Maybe also ability to use tor to host a local .onion address on the phone for a persistent and reachable address for BLW. Like a user could give me their reachable BLW address which would be a .onion and I could open a chan to them based on that. Even if not built in it could work with orbot which I believe has hidden services support.

I support BLW, and from research looks to be an excellent wallet. I just dont have a phone to test anything on. (I'm hoping to eventually get an android emulator working)

Thanks
Cannon

**Comment by btcontract** [comment]
> And I am aware of lnurl. I did consider lnurl but I did not want to install that functionality for security reasons. I was afraid of the extra software and reachable services opening up more security vulnerabilities and attack vectors

Fair, in defense of `lnurl-channel` I can say that it's a very self-contained and small protocol:
- at a minimum only a web-server responding with a static JSON piece is needed.
- web-server can be located at a different machne, no need to share space with LN node.

> A "connect only, await channel open from node" feature.

It's already planned to make it more clear that BLW can get incoming channels, not just open outgoing ones, will be implemented in next big update.

> Maybe also ability to use tor to host a local .onion address on the phone for a persistent and reachable address for BLW. Like a user could give me their reachable BLW address which would be a .onion and I could open a chan to them based on that. Even if not built in it could work with orbot which I believe has hidden services support.

This one sounds more like research topic, can't promise anything on this since too busy with higher priority stuff atm.
