### ISSUE TITLE
Be possible to open more than one channel with only one transaction.

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#31]
Be possible to open more than one channel with only one transaction.

**Comment by Perlover** [comment]
I didn't read about same opportunity in white paper of lightning network. This transfusion is named as funding. It's base transaction for channel. I think if it could be significantly complicate lightning protocol. And why to do it? This transaction will be big, fee will be big.

**Comment by fiatjaf** [comment]
There's no pint in doing it, if you think it is a good idea because you'll save the fee money, that will not happen.

**Comment by Kixunil** [comment]
@Perlover It's not complicated, the funding transaction is simply A sending BTC to 2oo2 address. A could send BTC to multiple 2oo2 addresses in single transaction and some wallets already do this.

@fiatjaf It will save on fees. If you open multiple channels using separate transactions, each open (except the last one, if you use `Max` button) needs to create change address which has to be in the blockchain only to be spent later and each transaction except the first one needs to spend an input which was generated in the previous transaction. Thus if you aggregate two channel openings, you save at least 68 bytes.

But there is entirely different reason for this also: you buy BTC with the wallet and then want to open several channels. If you do it one-by-one, you have to wait for confirmation before opening next channel in order for change to confirm. I was doing this past few hours - quite bad UX.

So I'm interested in this feature as well.

**Comment by btcontract** [comment]
@Kixunil btw there is a nicer working solution to this issue: https://github.com/btcontract/external-funder
The only thing left is for some exchange to actually implement it and this is the hard part.
