### ISSUE TITLE
Show on transaction popup, the % value of the fee paid in relation of total amount transferred

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#33]
Show on transaction popup, the % value of the fee paid in relation of total amount transferred

Ex: You paid a fee of 0.00001 btc, that is 1% of the total amount transferred in this transaction.

**Comment by bitcoinuser** [comment]
Copay has this implemented.
![screenshot_2018-04-11-00-04-34-1420973573](https://user-images.githubusercontent.com/1178856/38594310-0967b1c2-3d1c-11e8-8756-aacdfb475d0f.png)

**Comment by btcontract** [comment]
Implemented in https://github.com/btcontract/lnwallet/commit/b378964463cb89a211d6024b52e2cc27ce71988b
