### ISSUE TITLE
App appears to try to connect on default port regardless of setting

### ISSUE THREAD

**Issue by tyzbit** [btcontract/lnwallet#34]
I have two nodes on the same IP, one on port 19735 and one on 9735.

When trying to connect to the one listening on 19735, the app fails and in the debug log of the one listening on 9735 I get messages about authentication failed, indicating the wallet is trying to communicate using the pubkey for the other daemon on the default port.

Not sure what other information would be useful for debugging.

**Comment by btcontract** [comment]
Turned out wallet correctly tries to connect at port 19735, looks like the problem is on peer's side. Since https://github.com/btcontract/lnwallet/commit/83472bff7b18b4332c8678e2810de5b98d13834c wallet will be displaying tried host and port on connection failure.
