### ISSUE TITLE
payment webhook error

### ISSUE THREAD

**Issue by rafaelpac** [btcontract/lnwallet#35]
I was trying a LNbits LNURL-pay webhook forwarding, but it fails when using BLW (it works with other wallets).

It gives me error: "requirement failed: Action domain mismatch"

My webhook POST tests where directed at http://ptsv2.com/ and https://httpbin.org/post

**Comment by btcontract** [comment]
LNURL-pay spec mandates that domain for both endpoints must be the same (`url domain must be the same as `callback` domain at step 3`). BLW enforces this condition, apparently no one else does but it's not a BLW issue.

**Comment by rafaelpac** [comment]
True! Just saw it there. Closing this, thanks.
