### ISSUE TITLE
Mandatory Data Loss Protection

### ISSUE THREAD

**Issue by swilliams96** [btcontract/lnwallet#35]
All (but one) of the reachable peers in the peer list do not have "data loss protection" enabled so the app refuses to open a channel with almost all nodes since 4075645c99cf2fa21b1eb08deddbba72e180063e. The only peer that is reachable **and** has data loss prevention enabled is the _endurance_ node. However when trying to test transactions with [Starblocks](https://starblocks.acinq.co/) the payment fails as no route could be found through this peer (though I can successfully send transactions using [Yalls](https://yalls.org/)).

I realise that data loss protection is an important feature, but only being able to connect to one node halfway down the peer list isn't ideal. Especially if Olympus channel backups help to mitigate some of the risk that data loss protection solves?

**Potential Solutions:**
It might be good to only add peers to the peer list if they fulfil the required criteria that the wallet requires (in this case, mandatory data loss protection), so that users aren't provided with options that they cannot choose in the peer list. This might be something that needs to be implemented in the Olympus server code, not in the wallet client code, but I'm not sure.

Alternatively, a setting that makes data loss protection optional so that while other nodes/peers across the network implement this feature users aren't blocked from connecting to most peers by the wallet. This could be left off by default to improve the default security for users that do not switch this on in settings.

**Comment by btcontract** [comment]
> I realise that data loss protection is an important feature, but only being able to connect to one node halfway down the peer list isn't ideal.

Agreed but for now there's nothing I can do about it. LND is working on data loss protection so it should become a standard soon.

> It might be good to only add peers to the peer list if they fulfil the required criteria that the wallet requires

This is unfortunately not possible or at least not easy. Information about whether data loss protection is supported is only revealed once channel gets established, it is not present in general routing gossip which Olypus gets. Server would need to ping every node to find this out and I;m not sure it's a good idea.

> Alternatively, a setting that makes data loss protection optional

This somewhat complicates implementation but what's more important it enables a horrible UX where one channel can be recovered while other one can not. I really don't want users to think about these details that's why I've taken such a radical approach.

Also, other nodes with data loss protect: `03dc39d7f43720c2c0f86778dfd2a77049fa4a44b4f0a8afb62f3921567de41375`, `0387e89ea3fa2f73d6ec0293ab59114873db5113bfe0cc83083a4c3dc545e13265`

**Comment by swilliams96** [comment]
> Information about whether data loss protection is supported is only revealed once channel gets established, it is not present in general routing gossip which Olypus gets.

Ah this is a shame, but it makes sense. I agree, pinging every node is not feasible or sensible.

> it enables a horrible UX where one channel can be recovered while other one can not

I also agree here. Hopefully by the time we progress to mainnet there will be a larger number of nodes with data loss protection, and the proportion of peers that are compatible with the wallet on the peer list will higher which will mean a better UX.

Maybe in the future, wallets that fail to open channels with peers in the peer list could notify their Olympus server that a channel could not be created with that particular peer with the reason why. The Olympus server could then remove peers from its peer list for a short time if they receive a large number of notifications of channel creation failure in a short time. This would improve UX by minimising the number of wallets that are presented with peers that they won't be able to create channels successfully with at that time. This would also be useful for a number of different (temporary) channel creation problems, such as lack of data loss protection, the peer's lack of funds, or their fee rate requirements.

**Comment by swilliams96** [comment]
I'm leaving the issue open in case you want to add my previous comment's idea for channel creation failure notifications to the roadmap for the wallet and Olympus server. However, feel free to close it if this isn't something you want to add! :grin:

**Comment by btcontract** [comment]
No, there are no plans to allow wallets to influence server in any way for now as this can be easily gamed. Server/wallet communication should be always one way unless it's about storing backup data.
