### ISSUE TITLE
Error while using lnurl-auth with onion address

### ISSUE THREAD

**Issue by theborakompanioni** [btcontract/lnwallet#37]
Whenever I scan an lnurl-auth string with an onion url, it correctly displays the login dialog, but subsequently fails
with the following error when clicking the login button:
```
IOException: Cleartext HTTP traffic to <any_onion_url> not permitted.
```

App Version is 0.4.8-159 (with "Encore Tor is up on startup").
I have Orbot installed.

Am I missing something? Sorry if this is a misunderstanding on my end. Can you guide me into the right direction?

**Comment by btcontract** [comment]
Seems to be an instance of this: https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

**Comment by btcontract** [comment]
We're discussing this here also: https://t.me/lnurl/12762. Feel free to join if you have suggestions.

**Comment by btcontract** [comment]
Currently proposed solution is https://github.com/fiatjaf/lnurl-rfc/pull/74

**Comment by theborakompanioni** [comment]
I guess this is the way to go. Thank you.

I will try with a self-signed cert via onion in the coming days and will report back.

I am closing the issue.
Thank you for your time and efforts.
