### ISSUE TITLE
tried to redeem an lnurl resulting in error

### ISSUE THREAD

**Issue by vv01f** [btcontract/lnwallet#38]
Version 0.4.8-159 on Android 10

scanning an lnurl "voucher" holding 750,000.000 sats got me the error:

> Expected Long as JsNumber, but got "750000000"

I guess this needs a change on the data type.

**Comment by btcontract** [comment]
> I guess this needs a change on the data type.

yes, it looks like service provider has set the field value to string `"750000000"` where explicitly a number is expected (`750000000` without quotes). Wallet could try to get around this but it's a slippery slope, this should be fixed on service provider side, a typed Json response schema can be found at https://github.com/fiatjaf/lnurl-rfc/blob/master/lnurl-withdraw.md

**Comment by AryanJ-NYC** [comment]
Hey. I'm the service provider in this case. Great catch, @vv01f and thanks for the help @btcontract.

**Comment by vv01f** [comment]
thx y'all.
