### ISSUE TITLE
Segwit support not common enough yet

### ISSUE THREAD

**Issue by swilliams96** [btcontract/lnwallet#39]
Full segwit support is great and I support the adoption of segwit, however at the moment there just aren't enough services that support full bech32 addresses. For example, there are no testnet faucets that support native segwit addresses, meaning I (and others) can't even receive any tBTC to help test the wallet, without creating a new private key outside of this wallet app in order to get tBTC from a faucet to then use here to help test. 

This will be an issue on main net as well if this app is released in the next few months, as many block explorers and services still don't support native segwit addresses and forcing users to use it will limit the places that users' can transact with. I expect that this will only drive them to use alternative wallets instead, and not have any impact on encouraging businesses to adopt bech32 support.

I don't think the Bitcoin ecosystem is ready for native segwit addresses being forced at the moment - I think it would be better to allow users to choose between the two address formats on wallet creation, at least until there's more support from businesses and services in the space.

**Comment by btcontract** [comment]
Yes, I know, this is just another obstacle to wallet's usability for now.

The reasons I did this are:
- old wallet with legacy addresses had a very poor performance on mainnet and some obscure (although non-fatal) bugs which I did not know how to address.

- transition to native segwit addresses will have to happen at some point anyway since they allow for more further savings if nothing else, and it's much easier to do that while there are no mainnet users.

- I'm not a business which needs to get as much customers as possible as quickly as possible, I'm perfectly fine with people using other wallets for the coming months, this may even be a good thing.

**Comment by swilliams96** [comment]
Ah okay, performance and bugs are a sensible justification for this. I think this will be less of an issue on main net anyway so hopefully when this is released the impact will be smaller. 

> I'm perfectly fine with people using other wallets for the coming months, this may even be a good thing.

I think this would be sad. In my experience at least, this wallet is by far the smoothest and most performant. I think it would be beneficial to Bitcoin and would speed up adoption of the Lightning network if this had more users. But I see what you mean about not needed as many users as possible - you are not motivated by money and profits.

Perhaps as a middle-ground solution the option for P2SH-P2WPKH addresses to be generated could be allowed by the wallet but with a warning about this having some non-fatal bugs and to proceed with caution. Then if users desperately need to interact with a service that doesn't support native segwit addresses, they can still use the wallet in this case if they desire, but with the knowledge that the experience may not be as smooth as with native segwit addresses.

**Comment by btcontract** [comment]
>> Perhaps as a middle-ground solution the option for P2SH-P2WPKH addresses to be generated could be allowed by the wallet

This is technically hard as I'm using bitcoinj which is a quite complex software as is, I'm afraid this is not something I can technically handle.

**Comment by irekzielinski** [comment]
One thing that would be great is for the app to "see" SW P2SH balance (so I could fund the LN channel from native segwit or P2SH or maybe even legacy).

Reason:
Me (and possibly others) have a low value hot wallets.
I tend to import the same seed to different apps (like Coinomi, Eclair, this app). This allows for instant access to funds without need of wasteful moving funds on chain. When I imported seed to LnWallet - only bech32 balance was available for funding LN channel (others were ignored).
Would be great to remove this limitation if possible.

**Comment by btcontract** [comment]
Unfortunately this falls under "technically too hard" category. I'd have to bring back everything I've removed because it was causing a lot of issues.

**Comment by irekzielinski** [comment]
That's OK - not a big deal
