### ISSUE TITLE
Error when scanning lnurl-auth with HTTPS-Onion URI

### ISSUE THREAD

**Issue by theborakompanioni** [btcontract/lnwallet#39]
When scanning an lnurl-auth encoded HTTPS-Onion URI with the qr scanner the following errors shows up:
```
requirement failed: URI is neither Plain-HTTPS nor HTTP-Onion request
```

The cert is self-signed.
This was a test to mitigate the IOException when scanning HTTP-Onion urls reported in #37 .

Examples with a throw away onion address:

![image](https://user-images.githubusercontent.com/3358649/127344667-1f1a86fd-f8ad-4651-ba1e-35c694fcc3dd.png)

```
lnurl1dp68gurn8ghj76n0va68qcmk093hg6n9xek85mtc0pjx5ap5x4kkc6ttd9cxcafjwekh5vmfwfuhj6n3xd4kvuek0fcnyunew4jkzepwdahxjmmw9ashq6f0wccj7mrwv96hg6p0d3hkw6tw8a6xzeead3hkw6twye4nz0f4xqcr2vpsxucnqcfsxs6kzve3vcux2ctzxq6nwdfjvdnxvvfh8p3x2c33v5ur2vmrvcuxyc34xd3rjvfsx43nqvpjxfjrycnzv9skyt3hv7z
```

**Comment by btcontract** [comment]
Yes, this is expected. Current code strictly enforces either ca-signed clearnet `https` or `http` for onion addresses, as per spec. The plan is to get https://github.com/fiatjaf/lnurl-rfc/pull/74 merged, then update wallet code so this might take some time.

I'll provide an update here once it's all done.

**Comment by theborakompanioni** [comment]
Yes, indeed, I was expecting this when I tried.
I thought an issue is the best place to document this kind of stuff.

As of now, it seems there is no way for users to use lnurl-auth over tor in a convenient manner.
I'd really like to change that. But I guess it is best to clarify the spec at first.
I will continue playing around and eventually take part in the discussion on fiatjaf/lnurl-rfc#74 .
Self-signed certificates over tor will also display a cert warning. I guess there should be a way to make lnurl-auth work for HTTP over TOR even on android.

I'll leave this ticket open, if this is okay with you @btcontract .

**Comment by btcontract** [comment]
It now works in https://github.com/btcontract/wallet which is a successor of BLW.
