### ISSUE TITLE
"Invalid funding" error shown when <2 confirmations

### ISSUE THREAD

**Issue by swilliams96** [btcontract/lnwallet#4]
When trying to open a lightning channel with funds that only have 1 confirmation, the user is told they have "invalid funding" to open the channel. This may be confusing for newcomers.

If sufficient funds have been received into the wallet but the funds do not yet have the required 2 confirmations, the error message should instead tell the user that "2 confirmations are required to use funds when opening a channel". Potentially this could also include a link to an FAQ page on the lightning-wallet.com website that explains in a bit more detail.

<sup>(I'm happy to help with the FAQ if the website is open sourced somewhere, but unfortunately I don't know Scala well enough to implement the in-app part in a PR)</sup>

**Comment by btcontract** [comment]
> I'm happy to help with the FAQ if the website is open sourced somewhere
Thanks, here's the repo: https://github.com/btcontract/lnwallet-site

1 confirmation is enough for the funds to be spent but initial app version had issues with correctly displaying available amounts. I've issued a fixing update yesterday but maybe you're still using an old version. Anyway, today I'll issue another update which shows current app version so we'll see whether is issue is gone or not.

**Comment by btcontract** [comment]
Update `v0.01-5` is out (can be seen at menu -> wallet settings), it does not allow spending unconfirmed outputs and displays a balance in the following way: http://lightning-wallet.com/setting-up-bitcoin-wallet#how-bitcoin-wallet-displays-a-balance

Can you please check if the issue still remains?

**Comment by swilliams96** [comment]
Hi just tested, I can now successfully open a channel with funds from the faucet that have only 1 confirmation.
