### ISSUE TITLE
False positive dialog message on lnurl-auth error response

### ISSUE THREAD

**Issue by theborakompanioni** [btcontract/lnwallet#40]
I accidentally sent the following error response from an lnurl-auth action:
```json
{
  "status": "ERROR",
  "status": "Request could not be authenticated."
}
```

#### Expected behaviour
Dialog opens indicating an error

#### Actual behaviour
Dialogs displays "Authorization successful"

The code seems to rely on the "reason" field in the response.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/5782323da1729d51f05cdb05a5bd1b67e8913177 (will appear in v2 app update).
