### ISSUE TITLE
sometimes unable to make payment: Payment protection

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#46]
I have one channel open to bitrefill.com
I made a lot of successful payments to mainnet.yalls.org
Occasionally (maybe once a day) app will refuse the payment - saying something about payment protection not implemented. **If I try the same payment few times - it will finally start working again**.

I suspect there is some bug here - as it's unlikely that bitrefill.com switches on/off the payment protection flag.

**Comment by btcontract** [comment]
Is there anything special about there failing payments like high or low value? Do they all go to mainnet.yalls.org?

**Comment by irekzielinski** [comment]
I paid in some other places, but made most transactions in mainnet.yalls.org
It would work great for many interactions with yalls, and then suddenly buying another emoji (150 satoshi or so) will give me this error. I will try again and will get the same error few times in a row - one more time, and payment goes trough, and all subsequent ones.

Happened at least on three occasions now. I will see if there is a pattern (it might be after waking up device from sleep, but not sure).

**Comment by irekzielinski** [comment]
Opened a new channel with bitrefill - sometimes I can make a payment, sometimes not (payment protection issue). Noticed one thing: when "payment protection" error is raised - chanell is listed as OFFLINE in channel list. Could this be related to: https://github.com/ACINQ/eclair-wallet/issues/82

On minor request: "OFFLINE" message is displayed in green. Maybe would be better to do in in red?

**Comment by btcontract** [comment]
There is an error message when trying to send while all channels are offline but it looks like the following 
![photo_2018-06-11_10-31-46](https://user-images.githubusercontent.com/9870980/41218114-b1941428-6d62-11e8-8b0c-0a249a5b496b.jpg)

Are you sure it says about "payment protection" in your case? That would be the strangest part.

> On minor request: "OFFLINE" message is displayed in green. Maybe would be better to do in in red?

That's a good idea, currently color only depends on channel state but not on it's connectivity.

**Comment by irekzielinski** [comment]
yes - that was the message. I will try to reproduce it and capture as video.
Right now bitrefill appear to be "OPEN".

**Comment by irekzielinski** [comment]
unfortunately channel was force closed by LBW - can't seem to get a stable channel with Bitrefill.com

**Comment by btcontract** [comment]
Yes, LND based nodes currently have many issues with BLW, we are working on this.

**Comment by irekzielinski** [comment]
Over last 10 days I made around 60 payments with zero issues, beforehand this was happening quite frequently. I shall close this issue as appears fixed.
