### ISSUE TITLE
Minor UI improvement idea: indicate that invoice has been paid

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#47]
When receiving funds app will display a page with invoice (QR code).
After invoice is paid - would be great to have some indication on this page - maybe like a big green "Paid", when clicked invoice page could be closed.

**Comment by btcontract** [comment]
Looks similar to https://github.com/btcontract/lnwallet/issues/25 ? I like that idea more tbh: easier to implement and just as informative.

**Comment by irekzielinski** [comment]
sounds good :-) I will close this one.

**Comment by btcontract** [comment]
Added in https://github.com/btcontract/lnwallet/commit/d1702c7f51f561007926e5c24e5e5519262e0df7
