### ISSUE TITLE
Maximum amount button when funding a channel

### ISSUE THREAD

**Issue by swilliams96** [btcontract/lnwallet#5]
Adding a button that fills the input field with the maximum channel funding possible for the wallet in the channel-funding popup would help to improve user experience.

The button could implement the maximum channel size of 16,777,216 sats if the current available balance (with at least 2 confirmations) is _at least_ as high as that value, if not then it would fill the input field with the maximum _available_ balance (with at least 2 confirmations) in the wallet.

**Comment by btcontract** [comment]
This may sound strange but I don't want to push UI convinience and automatic stuff which makes decisions too far in this wallet. I'd rather prefer users to be conscious about what's going on and input an amount manually.

**Comment by swilliams96** [comment]
From what I can see you added some things to the UI on the "new channel" popup dialog to show the maximum available funds and maximum channel capacity which is much better. My main concern was that users had to first put in an amount and then try and see if it was within the channel limits; users weren't told the min/max requirements until _after_ they tried to continue and create the channel but this solves that. 😄
