### ISSUE TITLE
Payment expiry is too close to the current block height for safe handling by the relaying node

### ISSUE THREAD

**Issue by menzels** [btcontract/lnwallet#54]
i get this message in eclair wallet when i want to pay a lnwallet generated invoice.

i found this: "Eclair expects payment expiries to be strictly more than 7 blocks in the future, and the LN specifications defaults in BOLT11 is 9 blocks ."

i didnt find out what timeouts lnwallet uses by default, but maybe this can be fixed easily?

**Comment by btcontract** [comment]
BLW does not set a concrete expiry in it's payment requests so it is chosen by Eclair when a payment is attempted. 

It looks like Eclair selects a delay which is less than 7 blocks and then complains it's too short? @sstone please advice.

**Comment by menzels** [comment]
ah this lead me to here: https://github.com/ACINQ/eclair/pull/627 seems like the issue is known and being worked on.
