### ISSUE TITLE
feature request: specify node to connect to manually

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#56]
When opening a new channel there is a handy list of nodes to connect to.
Is there a way to specify something from outside this list (can't seem to find a way).
I want to connect to ln.zone (they run eclair node): 03480a3bbf56dea2fbeeabfe7fcfd1fbd6a4070e126f0f83106b06eca6fd3297cb@80.211.252.104:9735

So would be great to have an ability to specify url of my own choosing.

**Comment by irekzielinski** [comment]
It works - thanks! 
I guess it would made sense to add some buttons to the list of channels view as well.

**Comment by btcontract** [comment]
Added a QR button to channel opening view at https://github.com/btcontract/lnwallet/issues
