### ISSUE TITLE
Token payment fails

### ISSUE THREAD

**Issue by urza** [btcontract/lnwallet#57]
On testnet wallet with new payment channel open to LightningGemTest:
![screenshot_20180616-091259](https://user-images.githubusercontent.com/189804/41496681-fd73d2e8-7145-11e8-8943-e84751ea73e9.jpg)

**Comment by btcontract** [comment]
This is not necessarily a bug, could just be that there's no route from lightning gem node to https://explorer.acinq.co/n/03dc39d7f43720c2c0f86778dfd2a77049fa4a44b4f0a8afb62f3921567de41375 which accepts token payments.

Try to open another channel with node https://explorer.acinq.co/n/03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 to definitely get a payment fulfiiled.

**Comment by btcontract** [comment]
Can confirm this is a routing issue: I'm not able to fulfill https://starblocks.acinq.co requests when connected to lightning gem node only.

starblocks.acinq.co has a close channel connection with `03dc39d7f43720c2c0f86778dfd2a77049fa4a44b4f0a8afb62f3921567de41375` (token selling node) and both of them are currently not reachable from a part of network where lightning gem node is located.

**Comment by btcontract** [comment]
Closing this assuming an issue has been resolved.
