### ISSUE TITLE
Invoice value not filled when optional multiplier filed is not present.

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#58]
Here is an invoice for 400k satoshi that does not have multiplier filed (it's optional according to BOLT11). This invoice was generated by www.btcduke.com. When scanned by LBW - invoice is accepted, but number of satoshi was not filled into amount to send field.

lnbc4000001pdj8umapp5ca0kw6shl7qjqwjgyfln4x4m6545avljvaaky3hzvwnlqce5kkzqdq6xvungvf4xgunqwpjxu6rzvej8ycqpg2ku0c8qjv9lpen9meprva5hnfjjm20yujh74f2w88z6ms0j35f89yt4vkya0vp3tdrx0e8s8lg8nyn7r6n3u43xkq5frev0z43rrsscqjlaj27

Since then I contacted BTCDuke and they modified their code to use the multiplier. It might be an issue on some other websites though.

**Comment by btcontract** [comment]
> it's optional according to BOLT11

is it? https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#requirements-1 says that 

> A reader SHOULD fail if amount contains a non-digit or is followed by anything except a multiplier in the table above.

> A reader SHOULD indicate if amount is unspecified, otherwise it MUST multiply amount by the multiplier value (if any) to derive the amount required for payment.

**Comment by irekzielinski** [comment]
Hmm.... not 100% sure.
SHOULD - means it should be like this, but does not have to be (MUST is used when something is mandatory).

There is also a statement there:
`amount: optional number in that currency, followed by an **optional** multiplier letter`

So my understanding is that multiplier is recommended to be used, but not a MUST.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/bf5832e2ca0aa45d3caa0b44d370034c6167d9db
