### ISSUE TITLE
How can I connect to testnet?

### ISSUE THREAD

**Issue by micheal-swiggs** [btcontract/lnwallet#60]
Just wondering how I could run the app on testnet?

**Comment by btcontract** [comment]
There's a testnet edition: https://play.google.com/store/apps/details?id=com.lightning.wallet

App uses native segwit addresses which no testnet faucet recognizes yet so feel free to post a wallet address here if there will be problems with refilling.

**Comment by jsarenik** [comment]
I have both Eclair and this testnet wallet. I can receive from faucet on Eclair generated P2SH address and then send it from Eclair to bech32 address of this testnet wallet. Just that the transactions seem to be hanging in the air without confirmation.

TX ids on testnet:

f11e1608309229a58b68777140d9cc31fb0a233aeadcc166b4ed13d03f55d1d9

c2d41cae94208f7c3eaca3ebf9f2eadbff20f174cf90ac09f2f0c504aa92b889

2a4d3acac7373834d3e455b9165a178957d2e34c288194e45879425673feaba3

fedfc5b0c77d5f5726f42dddeadc184434ae27b3ad7c4f9a2cda94d87d355205

26d16da97da5bbcf2f1e698d93bcdbe22023b1098fa1f70961076c169ede0484

d7db8da3594fa2018d8c6dad0445d626c2dbe5a71e8baf021fd937fd362988b9

d814e254e27bfb53e32489f29159c62d29bdea589bb97f63e0cf256aca99237f

23f998f0763e5852f306fd87e7f14236be42d0f93afcdb4557f46a5383297840

ed0359d2361888651aa5490c8a0b94e5c8bdbb37ff92fe39ea401e2308a8189a

As you can see, I have tried to send different amounts and different fees, some even CPFP. None is in a block yet.

**Comment by stefan52a** [comment]
Same thing, waiting for 5 hours:
f950b30779d988cae4e34ff2c057bc795969402ff117b5dc3c4edcd18dec8075 
Not in a block yet!

**Comment by btcontract** [comment]
Not that I can do something about it, decision whether to include a transaction in a block is up to miners and on testnet miners behave extremely weird at times. I'm sure this will get resolved eventually.

FYI, testnet wallet supports external channel funding now, meaning you can get a channel funded from http://funder.lightning-wallet.com/funder/ without using Eclair as a proxy.
