### ISSUE TITLE
Problems with receiving payments.

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#64]
Hi Anton. 
I'm not sure if this is the best place but maybe you will be able to help here.
BLW works great to send payments (100% of time!) - but I was able to receive payments **only** from:
- https://www.coinpanic.com/Lightning/CommunityJar
- https://www.moneni.com/

As my channel gets depleted I was hoping to re-ballance it the "proper" way: by buing coins on the exchange and sending those via LN. I tried two exchanges:
- btcduke.com   (uses c-Ligthing)
- bitbargain.co.uk (uses latest lnd)

Both were happy to accept LN deposits, but failed to pay the invoices.
I contacted administators of both exchanges - but they were unable to diagnose the problem.
Both were able to reproduce the problem (as described below).

Steps to reproduce:
- use latest BLW wallet
- open channel to ACINQ 
- deplete the channel (used lnzone to do it)
- try withdrawals from community jar: should work OK
- try deposit in bitbargain.co.uk: should work OK
- try withdrawal (to pay LN invoice generated by BLW): error

This might be some incompatibility between eclair node ACINQ uses, or the way BLW works - not sure. Do you have any idea how to diagnose this?

I will send links to this thread to both dtcduke and bitbagrain admins I have been in touch about the issue.

Cheers,
Irek

**Comment by btcontract** [comment]
First thing which comes to mind is they may not recognize a routing hint which is contained in BLW generated payment requests. c-Ligthing definitely does not understand hints yet but latest LND should understand them.

Is it possible to find out what kind of error are they getting at bitbargain.co.uk? Is it "route not found at all" (does not get hints) or "no route can handle this amount at the time" (not a bug) or something else?

**Comment by irekzielinski** [comment]
@BitBargain could you extract relevant logs from the LND?

@btcontract: are you sure cLigthing does not support routing hints - quick glance at their source code reveals at least some level of handling it (and it has been there for quite some time): https://github.com/ElementsProject/lightning/blob/09c42037672d455869273f317c791ba95ba3942e/common/bolt11.h   see "routes" member in bolt11 structure. Not 100% sure if it's used properly.

Coinpanic (community jar) is using LND and this is their response to query: "how do you guys manage to route payments to BLW wallet": 

> I'm running the newest version of LND (development release), which has much better routing controls, although I don't think this is actually the reason.  The payment invoice contains routing hint information, and ACINQ is directly connected to my node.  Your payment invoice includes a hint to route through ACINQ, which I can see, and ACINQ knows to route to you.

This does not explain why bitbargain - that is also using latest version of LND fails to pay invoices

**Comment by btcontract** [comment]
"no route can handle this amount at the time" could be it. Can you try to send, say, 500 sat to @BitBargain and then ask for 100 back?

**Comment by irekzielinski** [comment]
> Hi,
> I looked for logs around the timestamp this happened and couldn't find anything relevant.
> Reading the issue page on Github, I think what Coinjar said about being connected to the Acinq node might help.
> I tried to do just that, but:
> $ l openchannel 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 1000000
> [lncli] rpc error: code = Code(205) desc = invalid chainHash (local=43497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea330900000000 remote=6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000)
> If you have any other nodes that connecting to might help, just let me know and I'll open some channels. Apparently a lot of the ones I had open before have been disconnected/terminated.
> Kind regards,
> BitBargain Support

It might be capacity issue - I can pay very small invoices (100 sat), but anything larger fails.
One of the errors was:


> x Unable to send coins: unable to route payment to destination: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc423634090)({ Signature: (lnwire.Sig) (len=64 cap=64) { 00000000 72 05 36 d4 80 b8 d5 61 51 e6 ea a9 eb 88 67 ff |r.6....aQ.....g.| 00000010 09 62 c9 05 6e 5d e8 9d d0 3e 94 b6 15 96 fa f2 |.b..n]...>......| 00000020 27 97 d9 18 d7 af 70 3d 5c 14 97 09 33 c0 37 c6 |'.....p=\...3.7.| 00000030 46 09 55 ff 36 96 7a 63 ab 62 47 4b fb 8b 3e 70 |F.U.6.zc.bGK..>p| }, ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, ShortChannelID: (lnwire.ShortChannelID) 524614:1872:0, Timestamp: (uint32) 1530109408, Flags: (lnwire.ChanUpdateFlag) 1, TimeLockDelta: (uint16) 144, HtlcMinimumMsat: (lnwire.MilliSatoshi) 1000 mSAT, BaseFee: (uint32) 100, FeeRate: (uint32) 1 }) )

**Comment by btcontract** [comment]
Yes, `TemporaryChannelFailure` signifies a capacity problem. This does not look like a bug in BLW since small payments can be routed.
