### ISSUE TITLE
Suggestion: Add a web page to show BWL usage statistics 

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#65]
I would like to see a webpage to show BWL usage statistics, like:

* Average time of all payments completed on BWL.
* Total (%) of payments failed compared to completed payments.
* Average of fees paid in %.

More ideas?

**Comment by btcontract** [comment]
I don't have an access to this data. Payments happen locally on devices and statistics is not collected because this wallet tries to be as private as possible.
