### ISSUE TITLE
Question: reason to remove Pay and Close?

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#67]
Hi Anton.
Any reason to remove "Pay and Close" - I find it very useful (much faster to come back after payment).
Maybe you could re-add it if app was invoked by "lightning:ln......" URL link?

**Comment by btcontract** [comment]
To me, it was a rather distractive expirience, whereas earlier I could mindlessly tap "pay" now I have to think whether I want to pay or pay and quit.

**Comment by irekzielinski** [comment]
it did not make sense for all payments - I feel the same,
but if you click on invoice in a browser (via ligthing:.... url) - that was quite a nice thing
not a big deal, but was saving some time when paying for multiple times
