### ISSUE TITLE
I can't open channel. 299999 is too small and 300000 is too large

### ISSUE THREAD

**Issue by stasbar** [btcontract/lnwallet#69]
Hello.
I can't open channel with either 299999 (too small) nor 300000 (too large) satoshi. 
I need to enter value with decimal place like 300 000.000

**Comment by btcontract** [comment]
Can't reproduce this, can you provide more details such as phone model and Android version? Also what was an approximate on-chain balance?

**Comment by stasbar** [comment]
Pixel 2 and Android P, but I can't reproduce as well. It's strange but it looks like everything is working fine now.

**Comment by jpatterson** [comment]
Actually, it works now. My hunch is that it was because my balance had 0 confirmations.

**Comment by btcontract** [comment]
Yes, looks like this is the reason. On-chain funds become spendable once they reach at least one confirmation to harden an SPV-level security. I'll do a better explaining job in an app.

**Comment by btcontract** [comment]
Supposedly fixed in https://github.com/btcontract/lnwallet/commit/3b0088ef27a40e4b05c56cc72631d932252b1a7b, feel free to re-open if this issue pops up again.
