### ISSUE TITLE
(Bitcoin) and (Lightning) tabs

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#7]
Hi,

I think you should add two tabs called (Bitcoin) and (Lightning). Somehing like what Circle apps does but with (Messages) and (Transactions).

![photo5116190589916915689](https://user-images.githubusercontent.com/1178856/35064823-67939b9a-fbb2-11e7-90a6-a66a1a86852d.jpg)

**Comment by btcontract** [comment]
Implemented in https://github.com/btcontract/lnwallet/commit/202c154c74d768639ba4b0c90630fda6044d3010
