### ISSUE TITLE
Unable to complete the connection to Olympus server for backup

### ISSUE THREAD

**Issue by rdymac** [btcontract/lnwallet#74]
My BLW hasn't been able to complete the connection to (a) Olympus server for the backup service. The app attempts to do it on every send I make, but it shows an exclamation mark and the popup says "failed and refunded".

Android 5.1

**Comment by btcontract** [comment]
It seems like what fails here is a 1000 SAT automatic LN payment which acquires 50 storage tokens from Olympus, these tokens are later used to store channel backups. The most probable explanation is currently there is no payment route from your peer to a recipient node. What are the the peers you're connected to?

**Comment by rdymac** [comment]
I was only connected to ACINQ's 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f

Connecting to other two nodes right now: OpenNode and Y'alls

**Comment by btcontract** [comment]
Direct connection to ACINQ should work fine for that LN payment unless they had liquidity issues. Has it been resolved since yesterday, meaning, has the payment become fulfilled eventually?

**Comment by rdymac** [comment]
Connecting to Y'alls mainnet node worked for the Olympus payment to go through. Thanks for the help.
