### ISSUE TITLE
Cannot download APK from GitHub link

### ISSUE THREAD

**Issue by rdymac** [btcontract/lnwallet#75]
When trying to use the provided direct link GitHub shows:

“This file is too big to show. Sorry!“

Direct link to APK file: https://github.com/btcontract/lnwallet/blob/master/app/app-release.apk

**Comment by btcontract** [comment]
It only shows s download link when opened from desktop, apparently.

**Comment by rdymac** [comment]
Ok, I've just downloaded it in desktop. I want to see if it works in Androids older than 5.0

Any plans on porting to iOS?

Looking forward to see Electrum's way to integrate LN to their app, hopefully it will still work on old Androids as it does now. The more the options the easier it will be for the people to adopt LN where it is currently needed the most.

Thank you for this great app!

**Comment by btcontract** [comment]
An app uses API level 21 which requires at least Android 5.0. I would love to support older versions but there are substantial technical reasons for current settings. Closing this issue assuming it's resolved.
