### ISSUE TITLE
Suddenly I'm unable to pay, error: FinalIncorrectCltvExpiry

### ISSUE THREAD

**Issue by rdymac** [btcontract/lnwallet#77]
I've been paying to the same recipient/node for testing, but suddenly payments are failing and refunded. I've sent this same info the receiving part in case they made a change to their node today:

Payment hash: 78af3564af5bb456aa73df3eec406fa558db0841cb62d484a727ee92c73f5535

-

Your wallet
-->
Node ID: 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f, Channel ID: 579938507652136961, Expiry: 144 blocks, Routing fees: 0.010000% of payment sum + baseline 1000 msat
-->
Final payee: 03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e, Expiry: 154 blocks

-

Success(ErrorPacket(03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e,FinalIncorrectCltvExpiry(533514)))

**Comment by btcontract** [comment]
If this happens again it would be helpful to find out an exact time of payment so we can get a blockchain height at that moment.

**Comment by btcontract** [comment]
My wallet is not very helpful here saying vague things like "the hours ago". Perhaps I should add an exact time to debug info.

**Comment by rdymac** [comment]
Does this request show the height?

lnbc155u1pd4dz7wpp5tmay6qztw890dd5qgtzra7cc5pu4eefhja3tpfg3x0wdm2v0le5sdp5296kjcmtyp5kuan0d93k2grxdaezqvpvxqcrqvf4x5crqgzz23pscqzysrq6kh0ss8j6qatlszd9877yen3ez2jdq92v2taa8udeushgc9qms44637yraspjh7r6jne4vq4ayx4tv8880r8z9jqystx62w3r5ensqxsuzkw

It is expired by this time, though.

**Comment by btcontract** [comment]
Payment request has a time stamp of `1532398542` which translates to `07/24/2018 @ 2:15am (UTC)` or block `533364`. Final payee expiry is 144 (+ 10 added by BLW it make sure there's enough blocks in case of what) so payee should be OK with any height after `533508`. It was offered a `533514` but rejected it for an unknown reason.

Have you tried it again, is it still happening?

**Comment by rdymac** [comment]
It's just worked:

lnbc2m1pd4wsgdpp5v20aw32art70kvghav73zcdrp8pxp3ag6j3wsp39du3dqxtr5r4sdp5296kjcmtyp5kuan0d93k2grxdaezqvpvxqcryvpsxqcrqgzz23pscqzysq3taapry6a0kq4p642lsxea8t8lvucw7exh8dcs7zvcv6nmmtqjr672j3skpvmtkzwyfe2rykhdv757z4w4adr0keuldejgtm5yv6kqp29hkqu

Your wallet
-->
Node ID: 03e50492eab4107a773141bb419e107bda3de3d55652e6e1a41225f06a0bbf2d56, Channel ID: 584995161577881601, Expiry: 144 blocks, Routing fees: 0.250000% of payment sum + baseline 1000 msat
-->
Final payee: 03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e, Expiry: 154 blocks

**Comment by rdymac** [comment]
I shared this I found yesterday https://github.com/cdecker/lightning-integration/issues/3 , not sure if they were doing stuff with their node between yesterday and today which was preventing my BLW to pay to them, Y'alls was also failing to pay to them, I'll check with them to see if it was indeed something wrong on their side which has now being fixed.

**Comment by fdeledger** [comment]
I'm encountering this problem now (in Testnet):
case class FinalIncorrectCltvExpiry(expiry: Long) extends FailureMessage { def message = "payment expiry doesn't match the value in the onion" }
![payment_fail](https://user-images.githubusercontent.com/42088176/44304939-ec08e900-a39d-11e8-84fa-469e3f023bf2.png)

**Comment by btcontract** [comment]
@fdeledger just in case: an app you're using is not BLW but Eclair mobile: https://github.com/ACINQ/eclair-wallet

**Comment by fdeledger** [comment]
@btcontract Oh, OK sorry.  I just referenced through the issue under discussion. Anyway, I'll try to course it through to Eclair persons.  In any case, this is still a collective problem of lightning.  It's difficult to adopt the technology if its cumbersome to use like this.

**Comment by btcontract** [comment]
@fdeledger you're right, this exact issue may be due to a bug is a local wallet as well as in a remote payee's node. BLW had related bugs for some time but they have been eradicated by now, hopefully there are no unaccounted ones left.
