### ISSUE TITLE
"To be as node" feature for incoming payments?

### ISSUE THREAD

**Issue by Perlover** [btcontract/lnwallet#79]
Thanks for nice wallet!

But I have problem to explain my friend to use this wallet for incoming transactions from me. I understand the LN protocol and understand your idea: for incoming he should made some outcoming payments. It's because he creates channel with some random nodes and these random nodes will not put initiated bitcoins to his side. But it's very ugly idea: for getting of payments he should make payments before. Your wallet will not be widely used by people if they want to get payments from some people.

Question: in future will be there possible to make feature "to be as node"?

For example: I want to pay my friend for something. He installs your wallet, he doesn't have bitcoins. After he shows to me QR code of his node (BLW) and I create channel with him directly. I create channel so I make funding deposit. And after confirmations I can send to him micro bitcoins. Do you have plans about this? May be there should be supporting from Olympus server. But I think this feature should be if you position your wallet as wallet for incoming payments.

**Comment by fiatjaf** [comment]
This would be the best thing, if possible. 

As a side note, I've tried opening two channels with random nodes in the list of nodes and spending so money through them, but even then I'm not able to receive payments. Apparently these nodes don't allow their channels to be used in the reverse direction (including the ACINQ node).

**Comment by Perlover** [comment]
@fiatjaf ACINQ node allows it. I can get incoming payments through this node if I made some outgoing payments there

**Comment by btcontract** [comment]
It is planned to support dually funded channels once they become a thing and to also support incoming channels, such that a funder is a remote peer.

**Comment by Perlover** [comment]
@fiatjaf I checked note the ACINQ node and yes,  now i cannot get incoming payments even i made some outgoing payments. Is very strange because i saw this as worked.  I don't understand why i cannot :(

**Comment by Perlover** [comment]
Here my screenshot annot ACINQ node
https://www.dropbox.com/s/jxxuiygd5hept4r/Screenshot_20180801-173650.jpg?dl=0

**Comment by fiatjaf** [comment]
That's the screen I see, @Perlover.

**Comment by btcontract** [comment]
@Perlover a funding transaction needs to reach 6 confirmations for acinq node to enable receiving, is that the case?

**Comment by btcontract** [comment]
@fiatjaf 
> That's the screen I see, @Perlover.

For ACINQ also? I suppose a funding transaction for that channel already has 6 confirmations so there should not be a "peer not enabled receiving" message unless there's a bug somwhere.

**Comment by Perlover** [comment]
And noticing: 5 hours before when i run BLW it first time redeemed Olympus tokens by LN. May be this warning for ACINQ was because in that time (5 hours ago) there no were backup tokens and my channel didn't have backup on?
Screenshot BLW now: https://www.dropbox.com/s/l5rhz7kolsinw0p/Screenshot_20180801-222631.jpg?dl=0

**Comment by fiatjaf** [comment]
Well, it is working here now too. Some days ago it wasn't, but I'm sure the problem wasn't the number of confirmations.

**Comment by btcontract** [comment]
> And noticing: 5 hours before when i run BLW it first time redeemed Olympus tokens by LN. May be this warning for ACINQ was because in that time (5 hours ago) there no were backup tokens and my channel didn't have backup on?

Definitely no, storage tokens is a completely isolated subsystem which can't influence channels in any way.

It does not seem like there is some kind of bug in BLW because receiving was enabled eventually. One thing I can think of is ACINQ node was not sending an enabling message for some time and then it started to send it out as usual.

**Comment by btcontract** [comment]
Closing this as incoming channels are now supported.

**Comment by Kixunil** [comment]
Note to anyone wondering about this: the reverse channel needs to be private.

**Comment by fiatjaf** [comment]
How do you open a channel with lnwallet? I don't see the node id anywhere.

**Comment by btcontract** [comment]
@fiatjaf a special kind of QR code is going to be introduced soon which, when scanned, will get you an incoming channel. Using node id is overly cumbersome so I don't want to encourage this way.

**Comment by Kixunil** [comment]
@fiatjaf Unfortunately, as I found out it works only if you have some channel with the node already due to #108, which kind of defeats the purpose. However, if it satisfies your use case, you can simply get the IP address of your phone, then list the connections on remote server (LND) and get the ID. Yes, this is prone to MITM attacks - use at your own risk!

@btcontract is there any issue/PR/notification channel I can subscribe to watch this feature? I'm very interested in it!

**Comment by Kixunil** [comment]
Awesome, thanks! I look forward to it. I'd also like a link (not necessarily right now) to some docs about how to create the QR code and make it work with LND.

**Comment by Kixunil** [comment]
@btcontract ping for the doc about QR code. I've updated my wallet already.

**Comment by btcontract** [comment]
@Kixunil really soon. One company wants to provide incoming channel services and `lnurl` is their idea so they are going to publish all the docs and guides. Currently they are polishing their server side code.

**Comment by btcontract** [comment]
@Kixunil so it happened, here's the announcement: https://twitter.com/bitrefill/status/1083001163161706496?s=19

And `lnurl` protocol which Thor and BLW use: https://github.com/btcontract/lnurl-rfc

**Comment by Kixunil** [comment]
Awesome, thanks, I will definitely try to use it!

**Comment by LukasVinc** [comment]
I have kind of a similar problem, that is related to this i think.
I was trying to open a channel from my LND-node to my BLW.
I used: 
openchannel --node_key MYNODEID --local_amt 500000 --sat_per_byte 1 --private
and i get the error: peer MYNODEID is not online
while having BLW open and the screen on (channel online and bitcoin wallet online).
How do i figure out the ip and port of my BLW or is there another way of opening a channel?

**Comment by Kixunil** [comment]
@LukasVinc it's because of a bug described in #108. You can solve it by using LNURL. I have released a code to do that today: https://github.com/Kixunil/lnch-vekslak (Do a review!)
