### ISSUE TITLE
Fingerprint support 

### ISSUE THREAD

**Issue by bitcoinuser** [btcontract/lnwallet#8]
The app should give an option to access by fingerprint and not only by passcode.

**Comment by btcontract** [comment]
nah

**Comment by swilliams96** [comment]
@btcontract could I ask why not? It would greatly improve user experience.

If there's concern about it not being as secure, most apps continue using passwords/PIN codes as default and allow fingerprints as a non-default option that users can turn on in settings if they wish to. Besides, I'm sure a fingerprint is a lot more secure than the "123456" password a significant portion of users would end up using.

**Comment by btcontract** [comment]
Added in https://github.com/btcontract/lnwallet/commit/d7411fc46f60dd3e7d36378fc02edec1c6bfd11c
