### ISSUE TITLE
Receiving is not enable by peer

### ISSUE THREAD

**Issue by lcasassa** [btcontract/lnwallet#80]
What does that mean? I see it in the channel info view and I am not able to create a payment.

Thanks!

**Comment by lcasassa** [comment]
https://photos.app.goo.gl/zs2kuEhHZNnc2RsH9

**Comment by lcasassa** [comment]
You can find the node peer as Buda.com, I own it::
https://1ml.com/node/0282734a2ca9bdca61859c71efdc43234ea664ecba9a785f780c6eec8c80243b45/

**Comment by drunkenclam** [comment]
Is the peer a LND node? Are you on master?

I have the same problem, with LND master and current version of BLW.

**Comment by btcontract** [comment]
Probably once again an instance of this issue: https://github.com/lightningnetwork/lnd/issues/1347, LND works on a solution here: https://github.com/lightningnetwork/lnd/pull/1595.

**Comment by lcasassa** [comment]
Yes, I'm using lnd master. Thanks for pointing it out! Looking forward for the fix :)

**Comment by drunkenclam** [comment]
With current versions of BLW and LND (0.5 beta), I'n now able to receive payments in a channel that's connected to a LND node (despite the PR #1595 not merged in LND).

**Comment by btcontract** [comment]
Most likely you were online at the moment when a funding transaction got it's 6th confirmation. It's not that LND does not enable receiving at all currently but that it does it very unreliably.

**Comment by drunkenclam** [comment]
Ah ok... lucky me :P

**Comment by btcontract** [comment]
A workaround is implemented in https://github.com/btcontract/lnwallet/commit/65d667df578c8348f331b846edb564da13414a77, will be available since 0.2-80 update.
