### ISSUE TITLE
Minor: display TX count in channel details

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#83]
I like new channel overview. Old layout had a number of Tx that were sent/received displayed, new one does not have it any more. Would be great to get it back :-)

Cheers!

**Comment by btcontract** [comment]
There's already quite a lot of fields in each channel's card, what if I add a separate line on top which will be reporting a number of sent/received payments for all channels?

**Comment by btcontract** [comment]
Implemented in `0.3-105`
