### ISSUE TITLE
Funds lost! Stuck channel with stuck wallet that displays error non-stop

### ISSUE THREAD

**Issue by d4amenace** [btcontract/lnwallet#86]
Put a record of the refund channel transaction that is stuck in perpetual stock status.....funds gone!!!!!!
![screenshot_20180824-152528](https://user-images.githubusercontent.com/29969146/44608495-82337980-a7b9-11e8-9f34-d247cf7f702d.jpg)
....

**Comment by fiatjaf** [comment]
Have you tried the force close?

**Comment by d4amenace** [comment]
Yes. I haven't even been in contact with the developer. It has him stumped. He is contacting the note operator supposedly to try to get the money refunded but it doesn't seem like it's going to happen since that was 2 days ago.

**Comment by btcontract** [comment]
In summary: remote error got user's channel stuck in NEGOTIATIONS mode, force-close was not attempted but wallet data was erased instead and later restored with "channel recovery tool" used.

As of now remote peer sends an error in wallet's request to force-close a channel since wallet can't do it I after current channel state erasing.

**Comment by btcontract** [comment]
@slush0 your help would be appreciated here since your node is a remote peer. Can you provide logs for channel `a517c964f3fc4380c88aa11086716c31d48e0036e75c89be1dab26006f85fac9` and force-close it locally?

**Comment by d4amenace** [comment]
![screenshot_20180827-004748](https://user-images.githubusercontent.com/29969146/44737190-e8b8e000-aab6-11e8-9cc9-10f4154e9f3f.jpg)

This is the only thing I see now when I log into the wallet.

**Comment by d4amenace** [comment]
![screenshot_20180827-004727](https://user-images.githubusercontent.com/29969146/44737250-0dad5300-aab7-11e8-9e76-334b6f447429.jpg)
![screenshot_20180827-004741](https://user-images.githubusercontent.com/29969146/44737255-14d46100-aab7-11e8-9c9f-dc764c0e4e77.jpg)

This is the error message I received before I went into permanent emergency mode.

**Comment by btcontract** [comment]
What does it say now when tapping a "Show error report"?

**Comment by d4amenace** [comment]
![screenshot_20180828-121841](https://user-images.githubusercontent.com/29969146/44739128-937fcd00-aabc-11e8-9797-7223776653cd.jpg)
![screenshot_20180828-121828](https://user-images.githubusercontent.com/29969146/44739129-937fcd00-aabc-11e8-9217-d7f84aed80b8.jpg)

This.

**Comment by btcontract** [comment]
This is really strange. Given an error report it seems like this happens due to user action such as button tap but no such action takes place as far as I understand. Let's see if this will go away after tomorrow's planned update.

**Comment by btcontract** [comment]
An update has been uploaded about 10 hours ago, can you please update an app to check is this behavior persists?

**Comment by d4amenace** [comment]
I can access my wallet again but the continuous pop-ups of the slusho Channel is still saying fail and will keep popping up until they causes the emergency mode. They just pop up one on top of the other until they overload the app.

**Comment by btcontract** [comment]
a-ha, so that's what is causing it. I should implement a protection against remote `Error` spamming, another update will be soon.

**Comment by btcontract** [comment]
Another update is out. Can you please check if updated app still shows a lot of error popups?

**Comment by d4amenace** [comment]
Still there

**Comment by btcontract** [comment]
Can you try once again with connectivity turned off? So we can rule out remote messages as a source of this.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/94421fe035510b3bf8a7750407d78fd50aaa43b4
The reasons for remote peer to previosuly refuse to force-close a channel are outlined here: https://github.com/lightningnetwork/lnd/issues/1904
