### ISSUE TITLE
Hard coded testnet uri

### ISSUE THREAD

**Issue by TbLtzk** [btcontract/lnwallet#87]
Showing the funding transaction of an open channel opens smartbit on the testnet:

https://github.com/btcontract/lnwallet/blob/43b1cdf679cfa212e11786dd34fe8e282ea48e5a/app/src/main/java/com/lightning/walletapp/LNOpsActivity.scala#L221

I could fix this myself, but I'm not sure whether there is a consistent mechanism in the app to toggle between testnet and mainnet. Otherwise it simply comes down to omiting `testnet.`

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/4dbef4a1b61981e4f300a587900c24076792a062
