### ISSUE TITLE
Feature request: disable channel

### ISSUE THREAD

**Issue by irekzielinski** [btcontract/lnwallet#90]
I have few channels open.
Sometimes one channel will become unstable (payments get stuck when its used, requiring to wait the timelock before payment expires). The trouble is that wallet will keep trying to use this unstable channel for all new payments - leading to even more stuck payments.

Proposal:
- in channel list, allow to temporarily disable/ignore channel for routing purposes. This will allow me to keep it open (maybe will get better), but not route trough it

- if payments get stuck with one channel, maybe wallet should avoid routing through it for lets say 24 hours (if other channels can provide a route)

**Comment by btcontract** [comment]
> if payments get stuck with one channel, maybe wallet should avoid routing through it for lets say 24 hours (if other channels can provide a route)

That is what's happening already: once obtaining a list of route candidates wallet first picks a cheapest routes and then those which start which local channels which have less pending payments. Of course there is no guarantee this will always work: better routes may turn out to be incapable of routing at the moment or may not be found at all.

Overall this seems like another level of complexity on top of already complex interface. Perhaps it's better to just close channels with such peers?

**Comment by irekzielinski** [comment]
I agree that it possibly complicates too much.

>wallet first picks a cheapest routes and then those which start which local channels which have less pending payments

So if there is a cheaper route, but one that results in stuck payments - wallet will keep trying it first every time? This looks a bit like my recent experience where wallet was always trying to use "fairly cheap" node - and payments getting stuck

Maybe logic should be: if channel has stuck payments, dont use it if there is route with other channel (even if fees are higher)?

**Comment by btcontract** [comment]
> So if there is a cheaper route, but one that results in stuck payments - wallet will keep trying it first every time?

No, there is a double sorting: first, routes are ordered such that cheapest ones are on top, then a second round of sorting puts fee-channel routes on top on cheapest ones. The problem is routes through busy-channels are still there and still may be tried if previous routes fail so "bad" channel will still be tried but a bit later.

**Comment by btcontract** [comment]
I'm writing "bad" because it may not be a direct peer's fault, any routing node along a payment route including a final payee may be delaying a payment for various reasons (bugs, deliberate attack)

**Comment by btcontract** [comment]
There is also a hard cap on pending payments per channel, which is set to 25. Once a channel gets that many pending payments it won't be tried at all.

**Comment by irekzielinski** [comment]
From your description it should work in optimal way.
Cheers
