### ISSUE TITLE
Google play error code: -505

### ISSUE THREAD

**Issue by mercurytoxic** [btcontract/lnwallet#91]
![screenshot_20180916-095103](https://user-images.githubusercontent.com/739809/45591438-53fb2100-b996-11e8-831a-ef52e314d72d.png)

**Comment by btcontract** [comment]
This should be fixed as of last `0.1-67` update which was uploaded to Google Play yesterday but is still not available (to me at least). Not closing this for now, please let me know if this will persist even after the new update is rolled out to users.

**Comment by btcontract** [comment]
WHATS NEW section at google play should contain a single word: "bugfixes". That would mean the very last version is available.

**Comment by mercurytoxic** [comment]
I can see a single Bugfixes now, though still says 0.1 (not 0.1-67). Same 505 error though.

**Comment by btcontract** [comment]
Do you have a testnet and mainnet apps installed at once on a same device?

**Comment by mercurytoxic** [comment]
Yes, on my Nexus 6P I do have the testnet app installed but can't install the mainnet because of the 505.
On a second phone just installed both with no problems, mainnet first and then testnet.

**Comment by btcontract** [comment]
OK, I think it will persist until testnet app is removed. It can be reinstalled later once again once mainnet is there, can you try it?

**Comment by mercurytoxic** [comment]
Yes, that worked. Uninstalled **Bitcoin Lightning Wallet Testnet** then installed **Bitcoin Lightning Wallet**  sucessfully, after that installed the testnet one with no issues, thanks heaps for the help.

**Comment by btcontract** [comment]
Thanks for testing, this was a one time migration issue, won't be happening again.
