### ISSUE TITLE
Funding transaction is not viewed in mempool and bitcoin network

### ISSUE THREAD

**Issue by Perlover** [btcontract/lnwallet#92]
Hi,

Now i have v0.1-67 but i see problem in this and in previous version
And i have restored wallet from seed (may be this important, i don't know)

Description:

1) I don't have opened channels
2) I make open channel and choose "ACINQ node"
3) I choose Max amount and any comission (bug is in both variants)
4) After opening i try to see funding transaction (channes is OPENING status, 0/3) but if i make "View funding transaction" - the blockchain explorer doesn't find this transaction.

I wait, after make "Close channel", after i make rescan blockchain and after i can make new channel (old channels there are as SHUTDOWN). I tried to make many times but always i have same effect. I think transaction is not send to bitcoin network.

**Comment by btcontract** [comment]
Can you provide a raw funding transaction please? It can be obtained by tapping a transaction in a list and then you'll see an option in a popup.

**Comment by btcontract** [comment]
This funding transaction tries to spend a 2nd output from this transaction: https://www.smartbit.com.au/tx/6e0a1a32c981703b4df3210deabd1c9cc87ac8683fdfc904f6db7db443b3bb2b which happens to be already spent by another channel funding transaction a long time ago (Jun 11).

I think I understand what's going on here: inserting OP_RETURN in transactions solves exactly this problem and that spending transaction (https://www.smartbit.com.au/tx/3fe235e1d8fd39b5e06555d35dd8b53ec1c2f0c9b19bd7a2e24d9c3171a19a25) does not have an OP_RETURN. There was a short period of time just around then when BLW was not inserting OP_RETURNs and seems like you've got hit by it.

Looks like I'll have to try to fix this bug for good now. Meanwhile, if you want to get the money out of the wallet you can correctly restore a balance in Electrum or Samurai wallets by using a mnemonic code.

**Comment by btcontract** [comment]
Can you please try the following for the testing purposes:

1. Erase your wallet data and restore it from mnemonic code, then wait until it is fully synchronized. You should see an incorrect balance at this point which includes an already spent output.

2. Rescan blockchain via "gear" -> "Rescan blockchain". Will you see a correct balance in the end (less than in step 1) or is it still the same?

**Comment by Perlover** [comment]
I am restoring now from seed. I will let you know
But i want to notice that this BLW wallet (with bug) was restored in new device some days ago. But i restored from seed and used restoring from backup servers. And second noticing - when i restored channels (i got onchain transactions) a some time i used two devices (old & new). During restoring process the old device was in Flight Mode. After restoring when new device had onchain unconfirmed transactions i started in online old device (there were opened channels). May be there could be reasons for this bug? ;-)
Now the old device was shutdown (i did reset). So after restoring from seed now only one device will work.

**Comment by Perlover** [comment]
Now i did:

0) The screenshot before: https://www.dropbox.com/s/bcjg163ubrxmjv3/2018-09-17%2019.48.08.jpg?dl=0
1) In Application settings of Android i found the BLW and did clean cache & data
2) I started BLW again and it showed to me create/restore page
3) I entered the seed (the old device already offline forever)
4) I waited of syncing of blockchain. After syncing the screenshot: https://www.dropbox.com/s/dcloe17b50wdjkf/2018-09-17%2020.00.25.jpg?dl=0
5) I had same amount as i saw before cleaning
6) I tried to open channel and i have same problem - no funding transaction
The screenshot now is https://www.dropbox.com/s/gbqbhwseqpg6nri/2018-09-17%2020.01.11.jpg?dl=0

Now the BLW shows to me link of funding transaction as https://www.smartbit.com.au/tx/e22c51d5dc5e3dc3076e16574fd23f45f8c660fbcbfd3cf10e97b549447e282d

The transaction raw is:


01000000000104ff52d4ae2a0ddd015b9a207c1789361a6c00641a01b304f92e471916043a8d720000000000ffffffff9d052bb6551f395333e13e48f12ddc75a1750c3fbc6b361c963cf8dbb963b5f40000000000fffffffffe2b0790a9146118792306ded721afe5d980f23fbdd5af8ec824b5a03c187c830000000000ffffffff2bbbb343b47ddbf604c9df3f68c87ac89c1cbdea0d21f34d3b7081c9321a0a6e0100000000ffffffff02d8e8250000000000220020c81c9ea5feb1b00d2b171ef22d2e55406352d576d715715a9b5e6c4ebdcb03ef0000000000000000166a14353ab96a8d8985b48502ccceb0cbed65aab24c4802483045022100ec6f91784805e3fcfb616be9a3c87a80f451fbc6255ec2ba9eeba852760d19a002200a92fbaabcfe8075827e236e4b90b4a03b166abcba44821ad5a461d5199bcb380121021964d7cdb15d9c5088935d33f52336aed0a7c3e0961a8c4c5c4e3e9ac72e304d0247304402203a38edf4751a9c58532a9ead67f101829ab971d3c0524c261ab57a35418c664002207b93bd243ed7b65e6eac6a6101787a94a69c79fef73eb60ee09f10e5043808a201210256ef3f91cb44ace8853fb0ff9d10c324f63dbbba3de4f178b3c1d705456d889002473044022071f6b1ece702df2359ee541209ed56c86b3d37ecfd7af304e6d80f30bb006a8d02203223c46ab27ffed1259f6dc82c56dca5f2fd39c7e2d6baf25e1298b8704ad23001210385cefd3eb9911bc62bfb7180880b0abfd7fbf873523e616bd427de1753dcb2070247304402205ec8edc4ff52d838a40ba05712e8b2c71312859bc2e079e8427d317fb217f83c0220089cafd234388beed5c065d7e42edff6f97c09b9ca72375a1e21c49d66de9602012103d16ca7751e2cd609b353a30a0d7118f727ffc9641cc06bb5608dd051f6d77a2500000000

**Comment by Perlover** [comment]
If you need - i can send to private channel the seed. You can try to do it yourself ;)
I trust to you so if you will need the seed i do it. Later i will create new wallet, it's not problem

**Comment by btcontract** [comment]
That will help of course. Guess the best way to hand it over would be via encrypted chat in Telegram, my nick there is @Sooqakrisa. Feel free to offer your options if this one won't do.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/lnwallet/commit/0d3ba5cbed8b2f238364573ba4a5467ea84a2792 and https://github.com/btcontract/lnwallet/commit/386d5e614eb318948ba45ad9315148e6fd3aa121, will take effect since 0.1-74.
