### ISSUE TITLE
[Enhancement] Support Older Android Versions

### ISSUE THREAD

**Issue by adlai** [btcontract/lnwallet#93]
I see that in commit 755683b the minimum SDK version was raised from 16 to 21, breaking support for old devices (including mine). I was wondering whether it would be possible to implement the change in this commit in a manner supported by the old versions as well?

I've done Android development a few years ago and could probably implement this myself, if @btcontract thinks it is possible to implement for the old versions as well.

**Comment by btcontract** [comment]
API level 21 is used for easy multi-dex setup and for `FileProvider` API which enables to export QR codes and wallet snapshots securely. I'm not sure if API level can be lowered while keeping these features, but you are welcome to give it a try!

**Comment by adlai** [comment]
Thank you for clarifying; I'll close this issue, and if I do succeed, reopen it as a pull request ;)

**Comment by btcontract** [comment]
Sure, feel free to ask if you run into any issues.
