### ISSUE TITLE
Obtain reason for failure?

### ISSUE THREAD

**Issue by iljah** [btcontract/lnwallet#96]
I've gotten several lightning payment failures, would it be possible to get more info about those from the wallet? For example why did it fail, which node caused it, etc...

What's the difference between refunded and frozen?

**Comment by btcontract** [comment]
> I've gotten several lightning payment failures, would it be possible to get more info about those from the wallet?

Yes, once a payment gets failed you can tap on it in a payment list and then "Share debug info" in popup window. The trick is debug info is not persisted anywhere and only accessible at runtime so it can only be obtained once a payment is failed, it won't persist after app restart and "Share debug info" won't be visible then.

> What's the difference between refunded and frozen?

Frozen is an off-chain payment which has been in-flight at the moment when channel got broken. It will either be fulfilled off-chain later or refunded on-chain once it's delay gets cleared. When you see a frozen off-chain payment you should also see a pending on-chain refund in a payment list. That refund value should be equal to frozen payment's amount minus on-chain miner fee. Is this the case?

**Comment by iljah** [comment]
> "Share debug info" won't be visible then

That explains why I remember seeing them but don't anymore

> equal to frozen payment's amount

I think this is what happened to me, just that it wasn't clear from UI.
Thanks!

**Comment by btcontract** [comment]
> I think this is what happened to me, just that it wasn't clear from UI.

Agreed, this is perhaps the most mind-bending part of LN. Perhaps one day I'll come up with a better way to represent them on UI.

**Comment by iljah** [comment]
Perhaps frozen payment could have a view refund button that would behave 
as-if user had clicked the corresponding refund transaction from main 
view? So it would switch to popup of refund transaction instead of 
frozen transaction.

**Comment by btcontract** [comment]
Thing is, we can't dismiss that frozen off-chain payment until corresponding on-chain refund gets broadcasted because depending on your peer's actions you may get that frozen payment confirmed off-chain (and corresponding on-chain refund will fail then). 

And in some very specific conditions you may even get both off-chain payment and on-chain refund confirmed. You will get some free money then at peer's cost.
