### ISSUE TITLE
Missed amount on received transaction

### ISSUE THREAD

**Issue by the9ull** [btcontract/lnwallet#97]
In the transaction details page it is shown.

![photo_2018-10-15_11-08-13](https://user-images.githubusercontent.com/1118740/46941361-3a1f2d80-d06b-11e8-93f1-4d7379ebe795.jpg)

**Comment by btcontract** [comment]
It could got shifted to the line below and thus became hidden. Could you please do the following: make system wide font size smaller than it is now and open an app again, will payment sum be there?

**Comment by btcontract** [comment]
There is already an instruction to ellipsize a text if it overflows but apparently not all models respect it. I've made such that sum has more room in https://github.com/btcontract/lnwallet/commit/1583872236f2744c2d8f484fe7bbbe7586e43344, please let me know if that fixes an issue after next `0.2-77` update.

**Comment by btcontract** [comment]
Has it been fixed in recent updates?

**Comment by the9ull** [comment]
> Has it been fixed in recent updates?

Yes
